### ISSUE TITLE
设置Cookies 无效

### ISSUE THREAD

**Issue by CL545740896** [g1879/DrissionPage#1]
Cookies 是HttpOnly 的  ，设置无效 ，但是使用selenium 设置，然后刷新页面 就有效

**Comment by g1879** [comment]
> Cookies 是HttpOnly 的 ，设置无效 ，但是使用selenium 设置，然后刷新页面 就有效

谢谢反馈，可以告诉我是哪个网站吗？

**Comment by CL545740896** [comment]
https://xiumi.us

**Comment by g1879** [comment]
> https://xiumi.us

找到原因了，不是HttpOnly的原因，是selenium add_cookie()时自动在domain前加了一个'.'，导致未能覆盖浏览器新产生的cookie，如果set_cookies()前先delete_cookie('sid')，就能正常登录。
我想想解决办法。
可以给你设置有效的selenium代码我看看吗？可以加QQ详谈吗？178691442。谢谢。

**Comment by g1879** [comment]
> https://xiumi.us

临时解决办法：
cookie = {'sid': 'xxxxxxx'}
page.get('https://xiumi.us')
page.driver.delete_cookie('sid')  # 加上这句
page.set_cookies(cookie)

这个cookie二级域名前没有'.'，而selenium添加cookie时会自动加'.'，所以不能正确覆盖。
下个版本对这种情况做适配，目前可以先手动删除这个cookie，这样写也不会影响新版本的兼容性

**Comment by g1879** [comment]
> https://xiumi.us

临时解决办法：
cookies = ({'sid': 'xxxxxxx'}, ....)
page.get('https://xiumi.us')
page.driver.delete_cookie('sid') # 加上这句
page.set_cookies(cookies)

这个cookie二级域名前没有'.'，而selenium添加cookie时会自动加'.'，所以不能正确覆盖。
下个版本对这种情况做适配，目前可以先手动删除这个cookie，这样写也不会影响新版本的兼容性

**Comment by g1879** [comment]
> Cookies 是HttpOnly 的 ，设置无效 ，但是使用selenium 设置，然后刷新页面 就有效

v1.7.8已修复这个问题，请试一下

**Comment by luohuaweishui** [comment]
设置cookie以后，显示未登录。设置cookie无效。。
