### ISSUE TITLE
连接浏览器失败,windows10

### ISSUE THREAD

**Issue by Galiathuss** [g1879/DrissionPage#105]
系统是windows10 
python3.10.11
DP version : 3.2.35

使用的测试代码
```
from DrissionPage import ChromiumPage

page = ChromiumPage()
page.get('http://g1879.gitee.io/DrissionPageDocs')

```

会报错:
![82bb51f3beb4a8432e66b0ff8888d67](https://github.com/g1879/DrissionPage/assets/37834529/b4c516aa-117b-4a5c-8e56-ece2b387b1e7)

具体情况:
1.运行后会出现chrome页面,但是不会执行访问,然后过了几秒就出现报错了
2.同样的代码在另一台电脑上可以运行,系统是win11,python版本和dp版本一致
3.尝试了其他端口,也尝试了关闭浏览器,但还是一模一样的报错

不太清楚这是为什么 麻烦大佬看一看

**Comment by g1879** [comment]
没找到浏览器文件，手动指定一下。
还有升级一下4.0的最新版吧。

**Comment by Galiathuss** [comment]
我按照文档中的方法指定过,指定过chrome和edge 都是一样的情况
```
from DrissionPage.easy_set import set_paths

set_paths(browser_path=r'这里修改为您的浏览器可执行文件路径')
```
路径来源是直接copy ``chrome://version``的

另外我使用option参数也指定过 也是一样的原因
和操作权限有关系吗


4.0我看有些api改动了所以还没来得及仔细看
