### ISSUE TITLE
使用nohup出現DrissionPage.errors.BrowserConnectError 問題

### ISSUE THREAD

**Issue by Tspm1eca** [g1879/DrissionPage#106]
環境：

- Debian version: 12 
- python 3.9.2
- DrissionPage 4.0.0b34
- chromium-browser 113

在正常情況下`python script.py`，程序退出沒有任何問題。

但當使用`nohup python script.py &` 時， 當程序退出後100%會出現以下錯誤：
```
DrissionPage.errors.BrowserConnectError:
127.0.0.1:9222浏览器无法链接。
请确认：
1、该端口为浏览器
2、已添加'--remote-debugging-port=9222'启动项
3、用户文件夹没有和已打开的浏览器冲突
4、如为无界面系统，请添加'--headless=new'参数
5、如果是Linux系统，可能还要添加'--no-sandbox'启动参数
可使用ChromiumOptions设置端口和用户文件夹路径。
```

這個問題好像比3.x版本更嚴重了。

**Comment by g1879** [comment]
没有用过Linux不是很清楚，似乎是系统不释放进程。qiut()等几秒试试看。
解决的话请告诉我一下。

**Comment by Tspm1eca** [comment]
> 没有用过Linux不是很清楚，似乎是系统不释放进程。qiut()等几秒试试看。 解决的话请告诉我一下。

可惜不行，我這是我用的quit語句`page.quit(timeout=30, force=True)`。
而且在linux（無介面）下還有一個問題，就是不加`options.headless()`會出錯。

**Comment by g1879** [comment]
谢谢
