### ISSUE TITLE
Interesting interaction with lenovo software

### ISSUE THREAD

**Issue by M2ATrail** [g1879/DrissionPage#108]
I'll Google translate at end
So I have a Lenovo laptop, was running script using your library, and suddenly today it wasn't working, I kept restarting kernel and it wasn't working, but I could see that DP.chromeiumpage() had a process.
Well, turns out, it was reading the [Lenovo Vantage ](https://www.lenovo.com/us/en/software/vantage/)software as the browser for some reason
adding this in case it interests you.
![image](https://github.com/g1879/DrissionPage/assets/65313038/564aafac-7dbd-4959-a519-2eab987259e1)

最后我会用谷歌翻译
所以我有一台联想笔记本电脑，正在使用您的库运行脚本，今天突然它不起作用，我不断重新启动内核，它不起作用，但我可以看到 DP.chromeiumpage() 有一个进程。
嗯，事实证明，由于某种原因，它正在将[Lenovo Vantage]软件读取为浏览器
添加这个以防您感兴趣。

code for reference, but same problem was happening with just `dp.ChromiumPage()`
代码供参考，但仅 dp.ChromiumPage() 也发生了同样的问题
```
browser_driver_path = r'C:\Python\chromedriver-win64\chromedriver.exe'
browser_binary_path = r'C:\Python\chrome-win64\chrome.exe'
browser_user_data_path = r'C:\Python\chrome_user_data'

import DrissionPage as dp
dp_options = dp.ChromiumOptions()
dp_options.set_paths(browser_path=browser_binary_path,
                     user_data_path=browser_user_data_path)

dp_driver = dp.ChromiumPage(
    addr_driver_opts=dp_options)



```

**Comment by g1879** [comment]
谢谢，但我没法测试这个问题，DrissionPage会在注册表里找Chrome安装路径，可能是 Lenovo Vantage 正好在这个路径，或者 Lenovo Vantage 正好使用了DrissionPage选用的端口？

**Comment by M2ATrail** [comment]
我使用的是自定义路径，所以不太可能，只是发现它很奇怪，所以提到它，以防您有兴趣研究这个。

这种情况仅在 vantage 应用程序打开时发生，但如果关闭，则脚本可以正常工作。

我已经做了一些测试，这似乎是因为 Vantage 使用“Microsoft Edge WebView2”，并且您的脚本正在读取该内容而不是 chrome
附上视频。
我正在使用 GOOGLE 翻译，请原谅错误


https://www.swisstransfer.com/d/df532391-9936-49d8-ba87-aa5bfacd61eb


I'm using custom path so it is unlikely, just found it odd so mentioned it in case you're interested in looking into this.

This only happens when the vantage app open, but if it is closed then script works normal.

I've done some testing, and it seems to be because Vantage uses `Microsoft Edge WebView2` and your script is reading that instead of the chrome
Attaching a video.
I'm using GOOGLE translations so pardon errors
