### ISSUE TITLE
Proxy with authentication 

### ISSUE THREAD

**Issue by Redrrx** [g1879/DrissionPage#109]
Hello and thank you for your work, greatly appreciate it.

I would like to know if there's an implementation of proxy auth in order to use proxies like this format:

`  
 proxy = "http://user:password@proxyprovider.com:6969"
`

**Comment by g1879** [comment]
是的，目前无法直接设置这种代理，需要用插件实现，比如SwitchyOmega。

**Comment by dairoot** [comment]
> http://user:password@proxyprovider.com:6969

DrissionPage does not support proxies that require a username and password. You can use proxies that do not require authentication.
