### ISSUE TITLE
How can I Upload file in ChromiumPage

### ISSUE THREAD

**Issue by seastar8170** [g1879/DrissionPage#110]
Hello everyone
I want to know about upload file using ChromiumPage
This is selenium code   to upload file

    upload_file = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "1.jpg"))

    file_input = driver.find_element(By.CSS_SELECTOR, "input[type='file']")
    file_input.send_keys(upload_file)

**Comment by g1879** [comment]
查看这里：
https://g1879.gitee.io/drissionpagedocs/ChromiumPage/upload

**Comment by seastar8170** [comment]
Thank you for your help

Kind regard

Thank you
