### ISSUE TITLE
SPA应用怎么获取渲染之后的网页源码

### ISSUE THREAD

**Issue by markwzy** [g1879/DrissionPage#111]
page = ChromiumPage()
# 访问网页
page.get('http://xxx.com/')
page.set.window.maximized()
html_source = page.html # 这个获得的是未渲染之后的网页代码

**Comment by pedro-peixot0** [comment]
Man I tried running it and got a warning from my company that I tried accessing a porn website

**Comment by g1879** [comment]
还没渲染就获取了吧，等待一个渲染后才出现的元素，然后再获取。
