### ISSUE TITLE
不能操作自己手开的Edge浏览器

### ISSUE THREAD

**Issue by chillbest** [g1879/DrissionPage#116]
![Snipaste_2024-01-25_12-44-00](https://github.com/g1879/DrissionPage/assets/38272247/48b38eb5-8e91-4049-907e-7d735acbdcc7)

此方法测试后对Chrome有效，对Edge浏览器无效。

不使用此方法时，可以在新建的Edge浏览器中打开网页，也可以操作已被该库打开过的Edge浏览器。但不能操作自己用手新建的edge浏览器（Chrome可以）。

场景是：日常使用edge浏览器，但是偶尔需调用该库在已打开的Edge浏览器中 进行操作。

**Comment by g1879** [comment]
要设置用户文件夹路径吧，不然会和已打开的冲突。
