### ISSUE TITLE
加载配置文件ini时，报错

### ISSUE THREAD

**Issue by aylitat** [g1879/DrissionPage#118]
![image](https://github.com/g1879/DrissionPage/assets/48346244/a8d1c4ed-cc28-40c7-8bd0-f555280d5a7e)
代码在执行om = OptionsManager(ini_path)时，报错。
ini_path = 'F:/project/gp****bots/inis/da*****4@hotmail.com.ini' （已经脱敏）
跳入代码后，毫无征兆就结束进程了。
![image](https://github.com/g1879/DrissionPage/assets/48346244/56127c00-923d-480f-8a38-af4e44ab09e2)

**Comment by g1879** [comment]
最新版不需要ini了
