### ISSUE TITLE
Ubuntu下可以启动和使用，但是不显示浏览器

### ISSUE THREAD

**Issue by CaoN1Ma** [g1879/DrissionPage#119]
Ubuntu下可以启动浏览器，但是浏览器并不会显示，只会在任务栏显示一个tab
![QQ截图20240130173919](https://github.com/g1879/DrissionPage/assets/9567310/26557e8a-4cca-4a22-863d-fd49091fe0a3)
下面的是代码，浏览器选项已经保存为默认
`from DrissionPage import ChromiumOptions, ChromiumPage, WebPage`
`path = r'/opt/google/chrome/google-chrome'`
`# op = ChromiumOptions()`
`# op.set_browser_path(path)`
`# op.set_local_port(9222)`
`# op.set_argument('--no-sandbox')`
`# op.save_to_default()`
`page = ChromiumPage()`
`# page = WebPage()`
`page.get('http://g1879.gitee.io/DrissionPageDocs')`
`print(page.title)`
`page.quit()`

**Comment by g1879** [comment]
设置co.headless(False)试试

**Comment by CaoN1Ma** [comment]
> 设置co.headless(False)试试

试过了，还是一样的

**Comment by wxhzhwxhzh** [comment]
升级成最新版，需要

**Comment by CaoN1Ma** [comment]
> 升级成最新版，需要

4.0.4.5

**Comment by yxnwh** [comment]
大概你之前运行过，并且没有正常退出，然后再重新运行代码导致的，需要kill掉chrome的进程再重新运行代码

**Comment by luoxiao1008** [comment]
解决了吗？我也遇到了

**Comment by Keramatfar** [comment]
> Try setting co.headless(False)

Does not help me.

**Comment by Keramatfar** [comment]
> DrissionPage

where is this version? in pypi it is not available.

**Comment by g1879** [comment]
旧版判断Linux没有界面就会自动以headless启动，新版去除了这个功能。
