### ISSUE TITLE
text()和raw_text()方法在textarea区域的问题。

### ISSUE THREAD

**Issue by luoxh8** [g1879/DrissionPage#12]
你好，

我在angular编写的页面里面抓取数据，但是遇到了以下问题。

我通过id定位到了textarea元素，然后使用text()方法，但是获取出来的文本，被格式化了。enter字符变成了\t。
于是我通过raw_text()方法去获取文本，但是无法获取文本，其他的textarea文本可以使用此方法获取，同一个页面，就是当前元素的上一个。

目前我selenium编写的text()方法可以正常获取，并且有原始文本格式。

请问这个问题，如何解决，望解答。

**Comment by g1879** [comment]
需要看具体网页才能知道是什么问题。
