### ISSUE TITLE
用过一次访客模式后，无论怎么该模式都还是到访客选择的页面

### ISSUE THREAD

**Issue by dianxiaopao** [g1879/DrissionPage#123]
co.set_argument('--guest')
运行过一次后，无论如何设置参数，即使完全不带启动参数，重启电脑，重装 DrissionPage 包后，一直到浏览器设置访客页面，一闪而过

**Comment by g1879** [comment]
会复用之前的用户文件夹，co.auto_port()试试

**Comment by ChengGuang-Li** [comment]
我也遇到这个问题了， 打开浏览器 打开页面，然后一闪而过，不知懂页面和浏览器去哪儿了。但是看桌面任务拦又有一个chrome的图标，可是这个图标点了没有反应
