### ISSUE TITLE
上传到底是upload还是upload_list

### ISSUE THREAD

**Issue by hhsacsb** [g1879/DrissionPage#124]
formatted_names = [
                folder_path + file for file in image_files
            ]

             p.upload_list('css:#root > div > div > div.semi-tabs.semi-tabs-top > div > div.semi-tabs-pane-active.semi-tabs-pane > div > div.container--157qa', formatted_names[:-1])
             
我用upload()和upload_list都报错啊，这2个方法到底怎么用的，官方文档也没写清楚。
![Uploading 微信截图_20240205155926.png…]()

**Comment by hhsacsb** [comment]
![微信截图_20240205155926](https://github.com/g1879/DrissionPage/assets/33142546/0725ef3f-c80d-4585-9458-def8e848b9ba)

**Comment by g1879** [comment]
https://g1879.gitee.io/drissionpagedocs/ChromiumPage/upload/
