### ISSUE TITLE
linux下运行遇到错误后希望能主动kill掉当前的浏览器进程

### ISSUE THREAD

**Issue by yxnwh** [g1879/DrissionPage#127]
目前drissionpage在linux下遇到错误只会抛出错误信息，但不会主动结束浏览器进程，这就会造成再次运行代码就会出现各种各样的错误，希望能在报错的同时自动终止浏览器进程

**Comment by yxnwh** [comment]
直接修改\site-packages\DrissionPage\_elements\none_element.py文件
1.文件头加入
`import os`
2.每条`raise ElementNotFoundError(None, self.method, self.args)`语句（共有3条）的上方加入
`os.system('pkill chromium')
print('已终止chromium进程')`

非常的简单粗暴和实用😄😄😄

**Comment by g1879** [comment]
对异常的处理应该是业务代码中实现，库只要把异常报告出来就好了。
