### ISSUE TITLE
前端使用ServiceWorker进行的网络请求，DP监听不到

### ISSUE THREAD

**Issue by Ronghefeng** [g1879/DrissionPage#133]
![32c5e66a783c4bb59bee157642470056](https://github.com/g1879/DrissionPage/assets/42339196/8a08bfb3-1a48-4b46-9802-36d28c07abd6)

网站地址不太方便提供，不过请求前面带有这个标志的，page.listen 监听不到，其他请求有监听到，查了一下，这个标志标识这个请求是通过 ServiceWorker 处理的，希望作者有空可以看一下，如果需要提供原网站，我去征求原作者同意，QQ 私法，作者在评论区回复我一下即可

**Comment by g1879** [comment]
这种我没接触过，如果可以的话麻烦给我研究研究。我qq：178691442
