### ISSUE TITLE
低版本chrome运行案例报错，升级最新chrome正常

### ISSUE THREAD

**Issue by MAX0100** [g1879/DrissionPage#134]
DrissionPage.errors.CDPError:
错误：Target crashed
方法：Runtime.evaluate
参数：{'expression': 'navigator.userAgent;', '_timeout': 30}
版本：4.0.4.5
运行时间：1.6875
出现这个错误可能意味着程序有bug，请把错误信息和重现方法告知作者，谢谢。

**Comment by g1879** [comment]
是在什么操作的时候出现的？

**Comment by MAX0100** [comment]
> 是在什么操作的时候出现的？

网站提供的实例，在没有代理的情况下，get就报错 了
