### ISSUE TITLE
标签页加载失败陷入死循环/等待过久

### ISSUE THREAD

**Issue by coovy** [g1879/DrissionPage#14]
非常好用的工具，但是我在爬取某个网页的时候遇到程序运行停滞的情况，大概卡住了10个小时左右，后面经过排查，发现卡住的地方如下：

在DrissionPage\chromium_base.py中的stop_loading()函数定义中，这行可能会陷入死循环或者等待过久的时间，建议设置一个时间阈值
![image](https://github.com/g1879/DrissionPage/assets/96867690/d5c43835-9c6d-43a6-b81c-0f61f7728591)

**Comment by g1879** [comment]
谢谢，我没有遇到过这个问题，我研究一下。

**Comment by Dinggggg** [comment]
作者有想好解决方案了吗？

**Comment by coovy** [comment]
> 作者有想好解决方案了吗？

作者目前不知道什么进度，不过对爬取数据的要求不高，我就直接给线程设置超时时间把这个问题覆盖过了。顺便补充一下，这个问题出现的情况是我在主线程连接了浏览器，然后传给子线程，每个子线程创建一个tab运行，运行结束关闭tab。子线程运行过程出现这个问题的

**Comment by Dinggggg** [comment]
Cool，我也是多线程控制不同tab，发现tab加载页面超时不会中断。我暂时先在stop_loading()函数中加了个超时判定，后续看看开发者有无其他解决方案。

**Comment by g1879** [comment]
我最近挺忙的，还没时间修这个问题。

**Comment by g1879** [comment]
在gitee留言会比较及时看到，GitHub总是不稳定很少上。

**Comment by g1879** [comment]
可试试4.0.0b26。
