### ISSUE TITLE
Cannot pass cloudflare human verification

### ISSUE THREAD

**Issue by wo9999999999** [g1879/DrissionPage#141]
<img width="421" alt="Screenshot 2024-03-07 at 10 53 55 AM" src="https://github.com/g1879/DrissionPage/assets/32102069/a1b0dbac-0b45-48c9-ab83-b8051210fb7c">

Can not pass cloudflare human verification

**Comment by g1879** [comment]
点那个框框怎么样？

**Comment by wo9999999999** [comment]
不行.. 你可以試一下
[https://www.globalinterpark.com/login?lang=en](https://www.globalinterpark.com/login?lang=en)

> 点那个框框怎么样？

**Comment by g1879** [comment]
我重现不了，每次一打开网页它自动就success了。
