### ISSUE TITLE
能否添加可以在浏览器控制台执行js的方法

### ISSUE THREAD

**Issue by MrBZBZ** [g1879/DrissionPage#144]
我看到.click()方法中可以设置直接通过执行网页的js代码来实现点击按钮，但是我想实现程序能够在浏览器控制台自动执行js从而实现一些功能，比如设置cookie，请问您是否会考虑添加一个能使程序在浏览器实例里操作控制台执行js代码的方法呢？

**Comment by g1879** [comment]
直接page.run_js()、page.set.cookies()不就好了。

**Comment by Adou02** [comment]
> 直接page.run_js()、page.set.cookies()不就好了。直接page.run_js（）、page.set.cookies（）不就好了。

那如何让run_js()支持jquery语法 $这些呢
