### ISSUE TITLE
TypeError: requests.structures.CaseInsensitiveDict() got multiple values for keyword argument 'User-Agent'

### ISSUE THREAD

**Issue by mosqudoo** [g1879/DrissionPage#146]
运行到driver.new_tab(url=study)时报错：
TypeError: requests.structures.CaseInsensitiveDict() got multiple values for keyword argument 'User-Agent'

**Comment by g1879** [comment]
没有见过这个报错，具体是哪一行报出来的？

**Comment by g1879** [comment]
最新版已解决这个问题。
