### ISSUE TITLE
文档搜索功能查看不全

### ISSUE THREAD

**Issue by programday** [g1879/DrissionPage#149]
![Snipaste_2024-03-13_10-03-46](https://github.com/g1879/DrissionPage/assets/62821993/6dcc204d-a9ed-40ac-aa3e-a7a8657392d7)
当我在文档页面搜索cookies的时候显示还有49个结果，接下来当我点击显示全部结果的时候，跳转新页面
![Snipaste_2024-03-13_10-04-57](https://github.com/g1879/DrissionPage/assets/62821993/39d8303f-846c-48be-87af-470fca11a90e)
这里又显示没有任何结果，搜其他的也是没有任何结果，查找内容很麻烦
![Snipaste_2024-03-13_10-05-47](https://github.com/g1879/DrissionPage/assets/62821993/beda32ef-e37e-4a6b-bdac-9403bcb4517f)
这种如何解决？

**Comment by g1879** [comment]
已修复。
