### ISSUE TITLE
打开一个空浏览器，不能自动打开网址。提示连接浏览器失败

### ISSUE THREAD

**Issue by kingname** [g1879/DrissionPage#151]
操作系统: macOS
DrissionPage版本：DrissionPage==4.0.4.12

<img width="1629" alt="image" src="https://github.com/g1879/DrissionPage/assets/5440523/160a09e2-1429-4887-a5a3-1d6cd0bac64d">

**Comment by kingname** [comment]
<img width="803" alt="image" src="https://github.com/g1879/DrissionPage/assets/5440523/6eecd93b-6cd0-4f62-894b-96acbdb1eac4">

DrissionPage自动启动的这个浏览器，确实有--remote-debugging-port=9222 参数

**Comment by 2five0** [comment]
我也遇到相同问题了
win11
DrissionPage==4.0.4.13
Google Chrome | 122.0.6261.129 (正式版本) （64 位） (cohort: Stable)
-- | --
修订版本 | f18a44fedeb29764b2b5336c120fdd90ef1a3f5c-refs/branch-heads/6261@{#1057}
操作系统 | Windows 11 Version 23H2 (Build 22631.3296)
JavaScript | V8 12.2.281.22
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
命令行 | "C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --user-data-dir="C:\Users\***\AppData\Local\Temp\DrissionPage\userData_9222" --hide-crash-restore-bubble --disable-suggestions-ui --no-first-run --disable-popup-blocking --no-default-browser-check --disable-infobars --disable-features=PrivacySandboxSettings4 --flag-switches-begin --flag-switches-end
可执行文件路径 | C:\Program Files\Google\Chrome\Application\chrome.exe

raise BrowserConnectError(f'\n{ip}:{port}浏览器无法链接。\n请确认：\n1、该端口为浏览器\n'
DrissionPage.errors.BrowserConnectError: 
127.0.0.1:9222浏览器无法链接。
请确认：
1、该端口为浏览器
2、已添加'--remote-debugging-port=9222'启动项
3、用户文件夹没有和已打开的浏览器冲突
4、如为无界面系统，请添加'--headless=new'参数
5、如果是Linux系统，可能还要添加'--no-sandbox'启动参数
可使用ChromiumOptions设置端口和用户文件夹路径。

**Comment by 2five0** [comment]
我用修改端口号的方法解决了：
打开下面文件
C:\Users\***\AppData\Roaming\Python\Python39\site-packages\DrissionPage\_configs\configs.ini
address = 127.0.0.1:9222 
找到默认端口号，随便修改一个，例如：
address = 127.0.0.1:9111

**Comment by wxjrkm520** [comment]
https://github.com/g1879/DrissionPage/issues/190

可以看看我这个issue
在库的路径里：/.venv/lib/python3.9/site-packages/DrissionPage/_functions/browser.py 修改一下有可能解决问题

**Comment by hustwenchao** [comment]
使用上面的方法没有解决问题，修改config.ini改了一个端口，正常了。

**Comment by EvanZhou666** [comment]
> 使用上面的方法没有解决问题，修改config.ini改了一个端口，正常了。

我之前都没问题，今天使用就出现这个问题，按照你的方法成功解决了，很感激您！

**Comment by g1879** [comment]
https://drissionpage.cn/browser_control/browser_options#-set_browser_path
可尝试指定浏览器执行文件路径。
