### ISSUE TITLE
一个python运行时调用js运行时函数的设想

### ISSUE THREAD

**Issue by wjsw1781** [g1879/DrissionPage#152]
我的想法来源是这个库针对这个库本身对于dom结构层面的维护  本质上是cdp通过ws或者http进行通信的结果,此时这个通道已经打通,此时无论是拿html text 还是配合和改造选择器都很方便,但js运行时更多的函数和属性本质上没有进行使用,一个很明显了例子如果一个网站使用react开发,爬虫恰好懂react vue的框架和依赖搜集与触发机制,那么问题已经很简单了,关键的逻辑已经集中在如果合理的调用js函数了

比如某网站 直播间观众信息
![image](https://github.com/g1879/DrissionPage/assets/28215744/8f1fbf72-7b0f-47e8-ba38-f56c7b6ee07c)

两行代码直接获取
如果这个设想实现的话   那么python侧只要维护一个dispatch  js侧只要维护几个proxy递归感觉就能实现  我还没看源码  ,  在此立帖子,后续我会更新!!

**Comment by g1879** [comment]
run_js()就行吧。或者直接抓包？
