### ISSUE TITLE
new_tab 能否增加一个参数  表示线程thread_id

### ISSUE THREAD

**Issue by wjsw1781** [g1879/DrissionPage#154]
![image](https://github.com/g1879/DrissionPage/assets/28215744/5f883a77-aa13-41fc-a695-2258aa89aca9)

这样一来 代码里就能设置使用这个thread_id进行tab的获取了  这个逻辑上就闭环了  

即使开着线程池,  每个线程也能通过这个thread_id 进行获取本就存在的tab,  如果没有再开启tab  ,更加节省性能

**Comment by wjsw1781** [comment]
此时也可以实现上述功能  但是必须维护一个线程池大小的对象 提前开好这么多tab  每个线程通过各自的id去这个对象里面去操控自己的tab  但是感觉不如[DrissionPage]进行维护来的好

**Comment by g1879** [comment]
感觉这个功能应该在二开的时候做。
