### ISSUE TITLE
有没有人在centos无头下加载插件成功  

### ISSUE THREAD

**Issue by wjsw1781** [g1879/DrissionPage#156]
![image](https://github.com/g1879/DrissionPage/assets/28215744/4fe3e58c-62ab-4ef9-a2c3-f56b04ba3ae0)

最终命令行是有的 但是最终结果就是没有代理插件,  目前测下来window完全没问题 Linux主要无法看到画面  只能截图 实在不好观察

**Comment by yfowsoulhq** [comment]
大哥，解决了吗

**Comment by wjsw1781** [comment]
解决了   无头的bug  ubantu没问题  centos不行  
先保证无头启动没问题    中文路径不行   字体乱码必须解决  然后才能开始加载插件

**Comment by yfowsoulhq** [comment]
> 解决了 无头的bug ubantu没问题 centos不行 先保证无头启动没问题 中文路径不行 字体乱码必须解决 然后才能开始加载插件

我本身就是ubuntu的无界面系统，无头启动本身是可以的，不能加载插件不就是无头模式的问题吗。字体乱码是啥意思。我试了好久不太行。
