### ISSUE TITLE
异步并发的问题

### ISSUE THREAD

**Issue by Redrrx** [g1879/DrissionPage#158]
我尝试用 options = ChromiumOptions().auto_port(True) 设置启动不同的浏览器，并且让它们在各自的异步任务中运行。但是其中一个浏览器挂起了，只显示了一个空白的启动页面，而另一个则完全受控。后来，我尝试在不同的线程中运行它们，情况有了很大的改善。为了让一切都稳定下来，我不得不为每个浏览器设置独立的事件循环。

我是不是漏掉了什么？我应该以特定的方式进行并发处理吗？

Python 3.11, Drissionpage 4.0.4.13

**Comment by g1879** [comment]
auto_port()支持多线程，但不支持多进程。用多进程时可以指定端口范围以确保不会冲突。
