### ISSUE TITLE
如何获取新窗口

### ISSUE THREAD

**Issue by killerddd3** [g1879/DrissionPage#159]
例如，点击页面A中的按钮，打开了新的页面B，如何操作页面B。
selenium中类似代码
```
windows = driver.window_handles  
driver.switch_to.window(windows[-1])
```
DrissionPage version :4.0.4.13
OS: Windows 11 Version 23H2 (Build 22631.3296)
python version: 3.8.8
chrome : 122.0.6261.129 (正式版本) （64 位） (cohort: Stable)

尝试了get_tab和get_frame都无法获取新打开的窗口

**Comment by killerddd3** [comment]
DrissionPage version :4.0.4.13
OS: windows11
python version: 3.8.8

尝试了get_tab和get_frame都无法获取新打开的窗口

**Comment by theafromhua** [comment]
我也想知道，点击A页面，这时候弹出新的浏览器窗口，如何进行切换，之前用类似
    handles = driver.window_handles
    driver.switch_to.window(handles[1])
现在有什么方法吗

**Comment by g1879** [comment]
https://g1879.gitee.io/drissionpagedocs/ChromiumPage/tab
请多看文档。

**Comment by nitteo** [comment]
> 我也想知道，点击A页面，这时候弹出新的浏览器窗口，如何进行切换，之前用类似 handles = driver.window_handles driver.switch_to.window(handles[1]) 现在有什么方法吗

兄弟，可以了么？？怎么操作
