### ISSUE TITLE
如何实现ctrl+F的功能

### ISSUE THREAD

**Issue by OSinoooO** [g1879/DrissionPage#16]
测试ctrl+A的功能是正常的，但我有个需求是使用chrome的内置搜索功能，该如何实现呢

**Comment by danny1879** [comment]
只有很旧很旧版本的浏览器才能这样用，你这个需求是要怎样用？

**Comment by OSinoooO** [comment]
yq行业，有截图取证的需求，我也试过调用js方法“window.find”，再配合上page.ele("text=xxx")并为对应关键词添加标签，但某些特殊页面下仍然无法定位到关键词，而使用浏览器自带的搜索就能找到，所以想着能不能有什么方法调用搜索框

**Comment by g1879** [comment]
> yq行业，有截图取证的需求，我也试过调用js方法“window.find”，再配合上page.ele("text=xxx")并为对应关键词添加标签，但某些特殊页面下仍然无法定位到关键词，而使用浏览器自带的搜索就能找到，所以想着能不能有什么方法调用搜索框

可以用滚动功能，定位到元素后滚动到元素，然后调用截图功能截图试试。
btw，yq行业是啥。

**Comment by OSinoooO** [comment]
舆情：）
