### ISSUE TITLE
发送退格键删除字符时遇到问题

### ISSUE THREAD

**Issue by neypro** [g1879/DrissionPage#160]
我创建了一个函数来发送随机字符并在执行自动操作时删除一些字符，但我无法发送 back_space 键。 不起作用，似乎生成了一个奇怪的字符

ele.input(Keys.BACK_SPACE,clear=False)

![image](https://github.com/g1879/DrissionPage/assets/39423543/63facd7b-0f80-4fa5-a4e3-7a2d6e625063)

**Comment by g1879** [comment]
这个现象在某些输入框才会产生，我还不了解为什么。可以尝试用page.actions.type('BACKSPACE')替代。

**Comment by g1879** [comment]
已修复，升级最新版就行了。
