### ISSUE TITLE
页面加载问题

### ISSUE THREAD

**Issue by bhu34905** [g1879/DrissionPage#162]
网址：https://dapptest.mindnetwork.xyz/

![Snipaste_2024-03-20_10-16-48](https://github.com/g1879/DrissionPage/assets/90811820/137c79c1-90d0-41e8-a55a-117fad7636c0)

这部分属于加载的`<section></section>`

在page.html 也没办法看到相关代码，尝试用xpath也定位不出来（主要原因应该还是没办法加载）

请问有什么办法能够处理，重新load下页面之类的吗

**Comment by g1879** [comment]
我点connect wallet没反应。
我想可能是还没等待它出现就获取了html而已吧。

**Comment by bhu34905** [comment]
请问这种情况可以怎么解决，有办法从page重新加载吗？

我在page是能执行到connect wallet，但section 代码加载不出来
