### ISSUE TITLE
批量打开标签

### ISSUE THREAD

**Issue by lsdlh** [g1879/DrissionPage#163]
如何批量打开一些标签页，不用等待一个页面加载完才打开下一个

**Comment by g1879** [comment]
new_tab()

**Comment by lsdlh** [comment]
> new_tab()

for i in range(8):
    tab = page.new_tab()  # 新建标签页，获取标签页对象
    tab.get('https://baidu.com/')  # 用标签页对象对标签页进行操作
这样是等第一个tab加载完才打开下一个，我要的是不用等待同时打开

**Comment by g1879** [comment]
明白了，目前需要先批量new_tab()不填url，再批量get()
