### ISSUE TITLE
How do I run multiple browser instances in different threads to work in parallel?

### ISSUE THREAD

**Issue by GendalfXXX** [g1879/DrissionPage#166]
I want to run N number of browsers and then use them in parallel using threading, but when I call ChrmiumPage(), only 1 browser opens and all other threads do the same actions in it. How can I implement this?

`class InitDriver:
    def __init__(self):
        self.driver = self.init_driver()

    @staticmethod
    def init_driver():
        proxy_box = random.choice(
            requests.get('url').json()['proxy']
        )

        proxy = Proxy()
        proxy_path = proxy.create_extension(proxy_box)

        options = ChromiumOptions()
        options.add_extension(proxy_path)

        driver = ChromiumPage(addr_or_opts=options)

        return driver`
        
  `def main():

    for _ in range(count_thread):
        web_driver = InitDriver()
        t = threading.Thread(
            target=get_cf_cookie,
            args=(web_driver.driver,),
            daemon=True
        )
        t.start()`

**Comment by g1879** [comment]
https://g1879.gitee.io/drissionpagedocs/demos/functions/create_browsers
https://g1879.gitee.io/drissionpagedocs/demos/actual/multi_browsers
看这两个链接。

**Comment by Akshay-Shingala** [comment]
> https://g1879.gitee.io/drissionpagedocs/demos/functions/create_browsers https://g1879.gitee.io/drissionpagedocs/demos/actual/multi_browsers 看这两个链接。

I am not able to access this URL

**Comment by ytinyui** [comment]
[https://gitee.com/g1879/DrissionPageDocs/blob/master/docs/demos/functions/create_browsers.md](https://gitee.com/g1879/DrissionPageDocs/blob/master/docs/demos/functions/create_browsers.md)
[https://gitee.com/g1879/DrissionPageDocs/blob/master/docs/demos/actual/multithreading_browsers.md](https://gitee.com/g1879/DrissionPageDocs/blob/master/docs/demos/actual/multithreading_browsers.md)
You may visit these pages.

**Comment by AmineSlimani** [comment]
Links aren't working

**Comment by ytinyui** [comment]
> Links aren't working

Updated

**Comment by bynaji** [comment]
now it not work
