### ISSUE TITLE
请问是怎么做到这么真实的

### ISSUE THREAD

**Issue by cyb-start** [g1879/DrissionPage#17]
昨天才知道的DrissionPage，对比同一个chrome.exe同一个网站，昨天网站加了最高限制的Cloudflare ，会一直检查站点连接是否安全，全军覆没。今天网站下调了防护级别，DrissionPage可以正常访问，puppeteer可以访问但是被网站重定向到首页，Jvppeteer会被识别到卡在验证页面。可惜我不会python，看不懂是怎么操作的。目前是在使用抓包工具来比较。。

**Comment by NCLnclNCL** [comment]
> 昨天才知道的DrissionPage，对比同一个chrome.exe同一个网站，昨天网站加了最高限制的Cloudflare ，会一直检查站点连接是否安全，全军覆没。今天网站下调了防护级别，DrissionPage可以正常访问，puppeteer可以访问但是被网站重定向到首页，Jvppeteer会被识别到卡在验证页面。可惜我不会python，看不懂是怎么操作的。目前是在使用抓包工具来比较。。

can you give me that website?

**Comment by g1879** [comment]
我自己写的底层，不依赖chromedriver，没有特征会被识别。

**Comment by cyb-start** [comment]
> 

Sorry, I only saw your reply now.The website I was testing was https://www.hapag-lloyd.cn/zh/online-business/track/track-by-booking-solution.html.
At present, its Cloudflare protection level is not at its highest level. Edge browser can access it, but Huawei browser cannot access it. The version of Huawei browser is 12.1.3.303 | Kernel version: 99.0.4844.84.

**Comment by lizhen1412** [comment]
How did you solve this problem, and can you share it?
