### ISSUE TITLE
click动作偶现报错“js运行环境出错。”

### ISSUE THREAD

**Issue by wwzzaho** [g1879/DrissionPage#170]
在登录时点击勾选框偶尔会出现以下提示：

[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-Traceback (most recent call last): 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-  File "wps_login_2023_fantasy.py", line 805, in _login_by_password 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-    cef_d.m_driver.ele(agree_click_xpath).click() 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-  File "C:\ProgramData\Anaconda3\lib\site-packages\DrissionPage\_units\clicker.py", line 30, in __call__ 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-    return self.left(by_js, timeout, wait_stop) 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-  File "C:\ProgramData\Anaconda3\lib\site-packages\DrissionPage\_units\clicker.py", line 81, in left 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-    if can_click and not self._ele.states.is_in_viewport: 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-  File "C:\ProgramData\Anaconda3\lib\site-packages\DrissionPage\_units\states.py", line 53, in is_in_viewport 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-    return location_in_viewport(self._ele.page, x, y) if x else False 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-  File "C:\ProgramData\Anaconda3\lib\site-packages\DrissionPage\_functions\web.py", line 107, in location_in_viewport 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-    return page.run_js(js) 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-  File "C:\ProgramData\Anaconda3\lib\site-packages\DrissionPage\_pages\chromium_base.py", line 440, in run_js 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-    return run_js(self, script, as_expr, self.timeouts.script if timeout is None else timeout, args) 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-  File "C:\ProgramData\Anaconda3\lib\site-packages\DrissionPage\_elements\chromium_element.py", line 1418, in run_js 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-    raise RuntimeError('js运行环境出错。 ') 
[Mon Mar 25 15:59:55 CST 2024][INFO][step9-node(RunProgram)]-RuntimeError: js运行环境出错。

**Comment by g1879** [comment]
应该是浏览器有点卡了。
