### ISSUE TITLE
page对象无法自动切换到最新tab页，导致新tab页面的元素无法找到

### ISSUE THREAD

**Issue by doom2030** [g1879/DrissionPage#173]
场景：登录tab页面登录成功后，当前登录页面tab成首页, 在首页中点击某个元素跳转到一个新页面(新tab页)， 然后使用page.ele()无法查找到新页面的任何元素，已经确认page.ele()中的定位元素是没问题的

排查发现，当前的tab还是在首页中，即使我使用了page.latest_tab 还是 page.get_tab(0), 发现并未生效，因为我新tab页面的元素依旧还是未找到

**Comment by err6** [comment]
转到一个新页面(新tab页) -> new_tab = page.cick.for_new_tab() ?

**Comment by MalikWilliams1greher** [comment]
我也遇到了这个问题

**Comment by g1879** [comment]
https://drissionpage.cn/ChromiumPage/tab

**Comment by MalikWilliams1greher** [comment]
> https://drissionpage.cn/ChromiumPage/tab

点击网页标签 新开一个标签 DrissionPage 不会自动定位到新标签咋整

**Comment by aliwumi** [comment]
可以默认用page.latest_tab.xxx来操作页面，浏览器相关操作才用page
