### ISSUE TITLE
设置 cookie 报错

### ISSUE THREAD

**Issue by ZhangzhiS** [g1879/DrissionPage#175]
<img width="890" alt="image" src="https://github.com/g1879/DrissionPage/assets/31681505/41393d17-e183-41f2-86d7-d92d2cb5391b">
代码如图，设置 cookie 的时候报错了。
使用 run_js 的方式可以设置成功。

**Comment by ZhangzhiS** [comment]
<img width="1654" alt="image" src="https://github.com/g1879/DrissionPage/assets/31681505/f22f0a91-8c87-4804-82ce-6e93d9b6ec37">
这是报错信息和版本信息

**Comment by g1879** [comment]
收到，迟点修复。

**Comment by g1879** [comment]
4.0.4.21已修复。
