### ISSUE TITLE
滚动功能无效

### ISSUE THREAD

**Issue by cikichen** [g1879/DrissionPage#176]
我想在boss直聘翻页
```
        print("Scrolling to bottom...")
        page.scroll.to_bottom()
        page.set.scroll.wait_complete()
```
无法触发滚动

**Comment by wuxs2008** [comment]
是我，我也遇到了同样的问题，滚动几次后就会停止，需要手动干预

**Comment by wuxs2008** [comment]
后来采用了两次滚动的方法先解决了

**Comment by wuxs2008** [comment]
具体是这样处理的。
1、打开页面，不触发监听事件的处理：
加载页面-->刷新页面
2、针对微博的抓取
先滚动到最上面，再滚动到最下面（触发监听，并处理数据）
每5次刷新一次页面

这样基本可以保障不会中断。

**Comment by chenjunliangya** [comment]
我也遇到了同样问题  触发不了滚动

**Comment by g1879** [comment]
要看看滚动是页面触发还是容器元素触发，还有可以用actions来滚动。
