### ISSUE TITLE
iframe里面查找元素报错 ValueError: stat: path too long for Windows

### ISSUE THREAD

**Issue by doom2030** [g1879/DrissionPage#177]
iframe里面要查找元素，但是报错了，从报错信息看是否是iframe内容太长了？
<img width="572" alt="图片1" src="https://github.com/g1879/DrissionPage/assets/143238423/a1bcc23b-b6ab-4466-8a54-36ba6b3cb81b">
<img width="873" alt="图片2" src="https://github.com/g1879/DrissionPage/assets/143238423/78829b3d-fe23-447c-8b75-4922b8b07b4f">

**Comment by doom2030** [comment]
经过验证，发现不是元素无法找到，而是 ele.get_screenshot()这个方法有bug, 不管我如何调整path参数它任然还是报错的，我甚至连参数都不传依旧报错

**Comment by g1879** [comment]
是的，我迟点修复。

**Comment by g1879** [comment]
已解决，升级就可以。
