### ISSUE TITLE
弹窗错误

### ISSUE THREAD

**Issue by chenyang399** [g1879/DrissionPage#181]
自动确认弹窗的函数在chrome里面没有用，我的场景是下载chrome插件的时候需要确认下载的弹窗，不能自动确认

**Comment by lee003** [comment]
一样遇到了， 浏览器的弹窗 不是 js的弹窗 没什么办法点击。  检测弹窗函数 也找不到

**Comment by g1879** [comment]
弹窗是alert还是原始模拟的？看不到不知道什么回。
