### ISSUE TITLE
增加类似 playwright  调试功能

### ISSUE THREAD

**Issue by JQ-K** [g1879/DrissionPage#188]
playwright 有个很好用的功能就是 可以直接上手调试，这样选择元素不确定的情况下，可以直接返回结果

**Comment by JQ-K** [comment]
现在遇到一个问题 ，在鼠标悬停显示内容  playwright 可以这样选择     page1.get_by_role("textbox", name="请输入搜索内容").fill("茶叶")
但是 DrissonPage 我尝试选择了输入框 但是输入内容的时候 显示 TypeError: 'str' object is not callable

**Comment by g1879** [comment]
没看懂，请描述详细一些。
