### ISSUE TITLE
无webdriver特征 是不是和正常的用户浏览器环境一样

### ISSUE THREAD

**Issue by MaxBill** [g1879/DrissionPage#189]
请教下  无 webdriver 特征   是不是和正常的用户浏览器环境一样 就是不使用webdriver  完全使用cdp协议进行交互的

**Comment by Alan3344** [comment]
> 请教下 无 webdriver 特征 是不是和正常的用户浏览器环境一样 就是不使用webdriver 完全使用cdp协议进行交互的

https://drissionpage.cn/#-%E5%BC%BA%E5%A4%A7%E7%9A%84%E8%87%AA%E7%A0%94%E5%86%85%E6%A0%B8
