### ISSUE TITLE
抓包请求的时候 发现请求头里面没有Cookie  

### ISSUE THREAD

**Issue by Jayden666z** [g1879/DrissionPage#19]
抓包请求的时候 发现请求头里面没有Cookie

**Comment by g1879** [comment]
说详细点。

**Comment by 906051999** [comment]
> 说详细点。

我直接在浏览器器打开URL，通过F12的网络监听中XHR筛选内容，在请求标头中会有Cookie等一系列内容；
而通过DrissionPage的网络监听打印出的.request.headers中却没有Cookie，且缺失很多内容
