### ISSUE TITLE
启动浏览器失败问题（解决，待作者更新）

### ISSUE THREAD

**Issue by wxjrkm520** [g1879/DrissionPage#190]
macos 14.4

proxies={'http': None, 'https': None}
这段代码有问题导致无法启动，删除后就可以了

def test_connect(ip, port, timeout=30):
    """测试浏览器是否可用
    :param ip: 浏览器ip
    :param port: 浏览器端口
    :param timeout: 超时时间（秒）
    :return: None
    """
    end_time = perf_counter() + timeout
    while perf_counter() < end_time:
        try:
            # proxies={'http': None, 'https': None}
            tabs = requests_get(f"http://{ip}:{port}/json", headers={'Connection': 'close'}, timeout=100).json()
            for tab in tabs:
                if tab['type'] in ('page', 'webview'):
                    return
        except Exception:
            sleep(.2)

    raise BrowserConnectError(f'\n{ip}:{port}浏览器无法链接。\n请确认：\n1、该端口为浏览器\n'
                              f'2、已添加\'--remote-debugging-port={port}\'启动项\n'
                              f'3、用户文件夹没有和已打开的浏览器冲突\n'
                              f'4、如为无界面系统，请添加\'--headless=new\'参数\n'
                              f'5、如果是Linux系统，可能还要添加\'--no-sandbox\'启动参数\n'
                              f'可使用ChromiumOptions设置端口和用户文件夹路径。')
 
![图片](https://github.com/g1879/DrissionPage/assets/49952604/e1851b64-8e5c-49af-a51a-a060bae90d93)

**Comment by g1879** [comment]
可以升级试试。
