### ISSUE TITLE
有人可以教我如何像人一样移动鼠标吗？

### ISSUE THREAD

**Issue by riiiiiiki** [g1879/DrissionPage#193]
有人可以教我如何像人一样移动鼠标吗？

**Comment by doom2030** [comment]
> 有人可以教我如何像人一样移动鼠标吗？

直接固定一个距离，模拟拖动个10次，记录时间节点和距离，不就可以了嘛

**Comment by g1879** [comment]
https://drissionpage.cn/ChromiumPage/actions
