### ISSUE TITLE
run_cdp "Network.setCookies" error

### ISSUE THREAD

**Issue by linling1** [g1879/DrissionPage#196]
错误：Invalid parameters
方法：Network.setCookies
参数：{'source': [{'name': 'msToken', 'value': '6jm1b-46dptt04LSW_rvcGA4GMYcrNDuHxyp92JwtueYFPsA8tFiYgJZyCSmoGCxUtYi2cgpkv65rMPYniS4XcDQa7Xye3EEijp1PGXbqxah_xjxDLptvXAlmn0U7f1uWFIYfz9mLdiDvDQGlvA=', 'url': 'https://www.tiktok.com/@fcbayern'}], '_timeout': 30}
版本：4.0.4.3

code:

~~~
cookies = {
        "msToken": "6jm1b-46dptt04LSW_rvcGA4GMYcrNDuHxyp92JwtueYFPsA8tFiYgJZyCSmoGCxUtYi2cgpkv65rMPYniS4XcDQa7Xye3EEijp1PGXbqxah_xjxDLptvXAlmn0U7f1uWFIYfz9mLdiDvDQGlvA="
    }
if cookies :
    cookie_param = []
    for k, v in cookies.items() :
        cookie_param.append({'name':k,'value':v, 'url':url})
    page.run_cdp("Network.setCookies", **{
        "source": cookie_param
    })
~~~

在 selenium 是可正常调用的。 selenium 代码如下：

~~~
if cookies :
      cookie_param = []
      for k, v in cookies.items() :
          cookie_param.append({'name':k,'value':v, 'url':url})
      driver.execute_cdp_cmd("Network.setCookies", {
          "source": cookie_param
      })
~~~

**Comment by xiaozeng2296** [comment]
我执行Network.deleteCookies和Network.getAllCookies和Network.clearBrowserCache这三个是没有问题的，set的时候报错提示{CDPError}CDPError("\n错误：Invalid parameters\n方法：Network.setCookies\n参数：{'name': 'zzz', 'domain': 'baidu.com', 'path': '/a', '_timeout': 30}\n版本：4.0.4.21\n出现这个错误可能意味着程序有bug，请把错误信息和重现方法告知作者，谢谢。\n报告网站：https://gitee.com/g1879/DrissionPage/issues")

**Comment by g1879** [comment]
用set.cookies()。
