### ISSUE TITLE
click.to_download(DOWNLOAD_DIR, file_name)，headless模式，频繁发生PermissionError

### ISSUE THREAD

**Issue by snigess** [g1879/DrissionPage#197]
![image](https://github.com/g1879/DrissionPage/assets/87859994/a4c2356f-3a19-4b02-9f28-bf64accbbcb8)
page.ele("报表导出").click.to_download(DOWNLOAD_DIR, file_name)，headless模式，频繁发生PermissionError，请看看。
目标文件确认没有被占用

**Comment by g1879** [comment]
升级试试。
