### ISSUE TITLE
pyinstaller 打包的程序关闭时，主程序继续在后台，不会自动结束

### ISSUE THREAD

**Issue by xianxiaoyin** [g1879/DrissionPage#198]
我用pyinstaller 打包的程序 点击 ×关闭界面，但是主程序还是在进程中，不会主动退出，我用的无头模式

另外  ChromiumPage 实例化的时候不能用上下文管理器，这个有更新计划么？

**Comment by g1879** [comment]
关闭界面不会关浏览器的，暂时没有这个计划。
