### ISSUE TITLE
无法适应mac系统的调试

### ISSUE THREAD

**Issue by flowercoder** [g1879/DrissionPage#2]
drission.py中读了一遍，发现path写的有点死，用的是chrome.exe
目前mac中chrome的路径是/Applications/Google Chrome.app/Contents/MacOS/Google Chrome（无后缀）
标准selenium强制制定是能认这个路径的。
目前阶段只能先用别的了。

**Comment by g1879** [comment]
> drission.py中读了一遍，发现path写的有点死，用的是chrome.exe 目前mac中chrome的路径是/Applications/Google Chrome.app/Contents/MacOS/Google Chrome（无后缀） 标准selenium强制制定是能认这个路径的。 目前阶段只能先用别的了。

谢谢你的建议。我迟点改一下。
我没有mac系统，所以没有在mac上调试过。不过用DriverOptions()设置driver_path参数应该是可以的，因为有几个人问过我在mac中使用的问题，他们应该是能够用起来的。

**Comment by flowercoder** [comment]
> > drission.py中读了一遍，发现path写的有点死，用的是chrome.exe 目前mac中chrome的路径是/Applications/Google Chrome.app/Contents/MacOS/Google Chrome（无后缀） 标准selenium强制制定是能认这个路径的。 目前阶段只能先用别的了。
> 
> 谢谢你的建议。我迟点改一下。 我没有mac系统，所以没有在mac上调试过。不过用DriverOptions()设置driver_path参数应该是可以的，因为有几个人问过我在mac中使用的问题，他们应该是能够用起来的。

driver_path参数是好的，没任何问题，但是chrome设置确实没法工作。如果不调用drission.py的话应该没问题，目前我的问题是你的demo我也没法跑起来，所以没法看下去。

**Comment by g1879** [comment]
> > > drission.py中读了一遍，发现path写的有点死，用的是chrome.exe 目前mac中chrome的路径是/Applications/Google Chrome.app/Contents/MacOS/Google Chrome（无后缀） 标准selenium强制制定是能认这个路径的。 目前阶段只能先用别的了。
> > 
> > 
> > 谢谢你的建议。我迟点改一下。 我没有mac系统，所以没有在mac上调试过。不过用DriverOptions()设置driver_path参数应该是可以的，因为有几个人问过我在mac中使用的问题，他们应该是能够用起来的。
> 
> driver_path参数是好的，没任何问题，但是chrome设置确实没法工作。如果不调用drission.py的话应该没问题，目前我的问题是你的demo我也没法跑起来，所以没法看下去。

嗯，因为我没有mac，所以也不知道问题怎么解决，或者可以用原生代码生成driver对象，再传入Drission的方式使用，类似这样：
```
from selenium import webdriver
from DrissionPage import Drission, MixPage

# 用 selenium 原生代码创建 WebDriver 对象
driver = webdriver.Chrome()
# 把 WebDriver 对象传入 Drission 对象
dr = Drission(driver_or_options=driver)

page = MixPage(drission=dr)
page.get('https://www.baidu.com')
```

**Comment by flowercoder** [comment]
> 

可以了，问题可以close了，感谢🙏
