### ISSUE TITLE
Cannot decode Chinese text

### ISSUE THREAD

**Issue by T-Tiffanyyau** [g1879/DrissionPage#210]
#台北玩什麼#台灣#台湾旅行#旅行#travel#taiwan#台北#台北景點#taipei#陽明山海芋#陽明山繡球花
img_url: https://scontent.cdninstagram.com/v/t39.30808-6/433067842_822913106545134_7622479052659642360_n.jpg?stp=dst-jpg_e15&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xMjAweDEyMDAuc2RyLmYzMDgwOCJ9&_nc_ht=scontent.cdninstagram.com&_nc_cat=106&_nc_ohc=GKfqS1UoxiMQ7kNvgGh1Edp&edm=APs17CUAAAAA&ccb=7-5&ig_cache_key=MzMyNzYxMTQyOTk0MjIxNzc4OA%3D%3D.2-ccb7-5&oh=00_AfCSZGF0gggh91IZDVidSAcHxT3HVP4vzWPdL2lJ6laHnQ&oe=6636DFF4&_nc_sid=10d13b
Image saved as result/taipeitravel/taipeitravel_0.jpg
Traceback (most recent call last):
  File "c:\Users\e.py", line 92, in <module>
    parser.start_parse(download_num)
  File "c:\Users\e.py", line 49, in start_parse
    parser.download_text(post_text)
  File "c:\Users\e.py", line 71, in download_text
    f.write(text)
  File "C:\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]

**Comment by T-Tiffanyyau** [comment]
change the function def download_text(self, text): to  `def download_text(self, text):
    file_name = self.folder_name + '/' + self.account + '_' + str(self.post_idx) + '.txt'
    with open(file_name, 'w', encoding='utf-8') as f:
        f.write(text)
    print(f"Text saved as {file_name}")`

**Comment by g1879** [comment]
没看懂，这不是dp的报错吧。
