### ISSUE TITLE
How to switch to another iframe by XPATH, and click a button or something like that?

### ISSUE THREAD

**Issue by louissiu198** [g1879/DrissionPage#214]

**Comment by test4cz** [comment]
<iframe>元素是一种特殊的元素，它既是元素，也是页面，因此独立一个章节对其进行介绍。

与 selenium 不同，DrissionPage 无需切入切出即可处理<iframe> 元素。因此可实现跨级元素查找、元素内部单独跳转、同时操作<iframe>内外元素、多线程控制多个<iframe>等操作，功能更灵活，逻辑更清晰。

**Comment by test4cz** [comment]
https://www.drissionpage.cn/ChromiumPage/iframe/

**Comment by louissiu198** [comment]
I tried that,             WebDriverWait(driver, 15).until(EC.frame_to_be_available_and_switch_to_it((By.XPATH, '//*[@id="hcaptchaContainer"]/iframe')))
            WebDriverWait(driver, 10).until(EC.visibility_of_element_located((By.XPATH, '//*[@id="checkbox"]'))).click()
I need to target the Iframe in order to click the button. Drissionpage does not accept iframe console js. You can only run some specific js on the iframe console not the whole-page console

**Comment by g1879** [comment]
如果是异域iframe，先获取iframe元素，再使用这个元素在里面找button元素。如果是同域iframe，除了上面这种方法，还可以直接用定位符拿到里面的button元素进行操作。
