### ISSUE TITLE
Didnt work please help me 

### ISSUE THREAD

**Issue by frkncnblt01** [g1879/DrissionPage#221]
from DrissionPage import ChromiumPage

p = ChromiumPage()
p.get('https://nowsecure.nl')
i = p.get_frame('@src^https://challenges.cloudflare.com/cdn-cgi')
if i:
    i('.mark').click()

it is worked perfectly before today. what is the problem anyone help me ?

**Comment by M2ATrail** [comment]
they changed it from `.mark` to `.cb-i`
for reference @g1879

**Comment by frkncnblt01** [comment]
Thank you. This is perfectly working. But i need to fix another problem. When i bypassed cloudflare this way, website search bar didnt work ?? i searched everything on internet and didnt find anything. I wonder your opinion for that

**Comment by dopamines-001** [comment]
get the error
https://www.fanfiction.net/s/14330750/1/When-Dark-Things-Come
DrissionPage.errors.ContextLostError: 页面被刷新，请操作前尝试等待页面刷新或加载完成。

**Comment by g1879** [comment]
这个网站变化了。

**Comment by sahillimba** [comment]
> they changed it from `.mark` to `.cb-i` for reference @g1879
not working

**Comment by M2ATrail** [comment]
@sahillimba 
Yeah my code doesn't actually need to be that automatic and I just manually do it now, here is the check.
```
    while any(["needs to review the security" in your_driver.html,
           "additional verification required" in your_driver.html,
            "just a moment" in your_driver.title.lower(),
            'security check' in your_driver.title.lower()
            ]):
```
