### ISSUE TITLE
Same operation work in mode "d" but failed in mode "s"

### ISSUE THREAD

**Issue by Hanochhu** [g1879/DrissionPage#222]
***It's seem same way to locate element is ok, but why one work one doesn't?***

```python
page=WebPage()
page.get("http://spiderbuf.cn/h03/")

divs=[]
divs+=page.eles("c:margin-top: 10px;")

print(divs)
```
<img width="847" alt="image" src="https://github.com/g1879/DrissionPage/assets/52187558/121891eb-a553-489a-a2f2-970bffba24e4">

```python
page=WebPage("s")
page.get("http://spiderbuf.cn/h03/")

divs=[]
divs+=page.eles("c:margin-top: 10px;")

print(divs)
```

<img width="892" alt="image" src="https://github.com/g1879/DrissionPage/assets/52187558/4788118a-518b-4791-93f6-6224a843343d">

**Comment by g1879** [comment]
"c:margin-top: 10px;"不是正确的写法，恰好浏览器支持而已，在s模式是不能这样写的。要用css selector标准写法。
