### ISSUE TITLE
能否添加页面加载状态的判断？

### ISSUE THREAD

**Issue by songge8** [g1879/DrissionPage#23]
现在有wait.load_start()和wait.load_complete()两个页面加载状态的方法。
但是实际应用中页面加载完成可能的状态有：DOM构建完成，页面完全加载结束；DOM构建完成，JS动态加载中；DOM构建完成，JS动态加载数据完成。
在实际应用中发现DrissionPage的wait.load_complete()方法应该是以DOM构建完成即判断为加载完成，但实际很多网站会继续JS动态加载数据，所以wait.load_complete()后直接获取数据可能不完整。

puppeteer针对这种情况使用了几种判断，如下，感觉可以借鉴参考一下
`
await page.goto('https://www.baidu.com', {

   timeout: 30 * 1000,

   waitUntil: [

       'load',              // “load” 事件触发

       'domcontentloaded',  // “domcontentloaded” 事件触发

       'networkidle0',      //在 500ms 内没有任何网络连接

       'networkidle2'       //在 500ms 内网络连接个数不超过 2 个

   ]
});
`

**Comment by g1879** [comment]
谢谢，我研究一下。
一直没找到办法判断是否有JS在运行，谢谢提供思路。

**Comment by g1879** [comment]
新版监听器已提供listen.wait_silent()方法，可等待所有网络连接完成。

**Comment by crrongyan** [comment]
我有遇到同样的问题，doc_loaded()无法等待由js触发的页面跳转，十分宝贵的lssues帖。考虑到解决时间成本是否允许在文档中增加提示？
![截图](https://github.com/g1879/DrissionPage/assets/46481479/e227b48e-5b80-487a-aed6-1820ee750351)

**Comment by SinMu-L** [comment]
> 我有遇到同样的问题，doc_loaded()无法等待由js触发的页面跳转，十分宝贵的lssues帖。考虑到解决时间成本是否允许在文档中增加提示？ ![截图](https://private-user-images.githubusercontent.com/46481479/329449297-e227b48e-5b80-487a-aed6-1820ee750351.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjgzOTUsIm5iZiI6MTczNTEyODA5NSwicGF0aCI6Ii80NjQ4MTQ3OS8zMjk0NDkyOTctZTIyN2I0OGUtNWI4MC00ODdhLWFlZDYtMTgyMGVlNzUwMzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDEyMDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4Njc4MWZkMDk0NGJkNWFjMmNmNWQzYTY3Yjk2YjZiNTkzMDJlYzY1NTJmNmJhYTNmMjI4ZWQ1NjUyMTMzM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sgzp9ywIZyAka3Uij1jEx0MDga-noYkF_TBrzLwpHXI)

我也遇到了同样的问题，你有解决么？


按照 https://www.drissionpage.cn/browser_control/page_operation/#-setload_mode 中提到使用`set.load_mode.normal()` 没有达到预期的效果

**Comment by SwapnilSoni1999** [comment]
Have you figured out any way ?
