### ISSUE TITLE
Possible thread/memory leak on page.ele("some iframe selector") (+ others as well)

### ISSUE THREAD

**Issue by mr-wong** [g1879/DrissionPage#236]
page.ele("some iframe selector") / page.get_frame() / page.get_frames() calls create two threads named _handle_event_loop and _recv_loop per each iframe and don't terminate them. This might be a problem if you make hundreds of calls.

**Comment by g1879** [comment]
tab关闭后这些线程会自动关闭的。异域iframe关闭后也会，但同域iframe则要等tab关闭才会关闭。
