### ISSUE TITLE
作者列举的几个超时 能够详细解释下

### ISSUE THREAD

**Issue by wjsw1781** [g1879/DrissionPage#237]
def set_timeouts(self, base=None, page_load=None, script=None, implicit=None):
        """设置超时时间，单位为秒
        :param base: 默认超时时间
        :param page_load: 页面加载超时时间
        :param script: 脚本运行超时时间
        :return: 当前对象
        """
        
       能否举例说下每个超时所代表的意义

**Comment by g1879** [comment]
这个已经写得很清晰了，自己试试就知道了。
