### ISSUE TITLE
csdn 无头模式触发验证  有头模式没有任何问题

### ISSUE THREAD

**Issue by wjsw1781** [g1879/DrissionPage#239]
![image](https://github.com/g1879/DrissionPage/assets/28215744/b38996f6-b656-4601-bedf-b27310034594)

**Comment by wjsw1781** [comment]
url='https://blog.csdn.net/weixin_45366499/article/details/106943229'
while 1:
    all_url = first_tab.s_eles('xpath://a')
    if len(all_url)>0:
        break
    first_tab.refresh()
    logger.error(f'首页根本就没有url  进入队列   无法开启后续爬取 所以这里进行重试')
    first_tab.get_screenshot('first_tab.png')

**Comment by wjsw1781** [comment]
first_tab=page.new_tab()
first_tab.get(url,timeout=5,show_errmsg=False)

**Comment by wjsw1781** [comment]
已解决

**Comment by chen39137112** [comment]
如何解决的，求教

**Comment by g1879** [comment]
ua跟cdp没关系，无头启动就自动在ua里添加Headless。

**Comment by wjsw1781** [comment]
无头启动就自动在ua里添加Headless。

就是这个机制 导致被检测的
