### ISSUE TITLE
下载功能在某些场景下让人很苦恼，无法直接使用 @g1879 貌似很久没看issues了，大佬在忙嘛

### ISSUE THREAD

**Issue by doom2030** [g1879/DrissionPage#240]
在点击链接弹出新tab下载的情况下，使用 click.to_download(r'C:\Users\ADM1YuanZh\Downloads', new_tab=True)  和  download_mission = page.wait.download_begin() 均无效，返回值都是False, 文件虽然下载了类似 40823255-1c48-445a-96da-a96015f7cce1 这种，但是我想处理这个文件也要先获取到这个文件路径名称，但是DownloadMission对象一直是false， 没办法获取到下载文件路径，是否有其他解决方案呢？
![aaa](https://github.com/g1879/DrissionPage/assets/143238423/9d7d760f-de97-4463-bbe9-f1b93e339b7c)
![bbb](https://github.com/g1879/DrissionPage/assets/143238423/188ecb97-12ff-4907-8928-735db1018506)

**Comment by doom2030** [comment]
> 在点击链接弹出新tab下载的情况下，使用 click.to_download(r'C:\Users\ADM1YuanZh\Downloads', new_tab=True) 和 download_mission = page.wait.download_begin() 均无效，返回值都是False, 文件虽然下载了类似 40823255-1c48-445a-96da-a96015f7cce1 这种，但是我想处理这个文件也要先获取到这个文件路径名称，但是DownloadMission对象一直是false， 没办法获取到下载文件路径，是否有其他解决方案呢？ ![aaa](https://private-user-images.githubusercontent.com/143238423/332695097-9d7d760f-de97-4463-bbe9-f1b93e339b7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjMwMTQsIm5iZiI6MTcxNjM2MjcxNCwicGF0aCI6Ii8xNDMyMzg0MjMvMzMyNjk1MDk3LTlkN2Q3NjBmLWRlOTctNDQ2My1iYmU5LWYxYjkzZTMzOWI3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwNzI1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDUxNTNmZmZhOTQwNmZhMGUzMTZmNzdmZjhjNDRkZmY0MmE3MjU4MGE3Y2EwODUyN2U1M2UzNGU5NDdkMGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bEqvhEl2ALPRW_hDyhXzPywP-8sG7uGe291DsyNTjuI) ![bbb](https://private-user-images.githubusercontent.com/143238423/332695105-188ecb97-12ff-4907-8928-735db1018506.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjMwMTQsIm5iZiI6MTcxNjM2MjcxNCwicGF0aCI6Ii8xNDMyMzg0MjMvMzMyNjk1MTA1LTE4OGVjYjk3LTEyZmYtNDkwNy04OTI4LTczNWRiMTAxODUwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwNzI1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGJiYTRmOTk5NDIxODAzZDg1N2VmMjhhNWM1NThkNGViZTQ2MGI5MWFkN2JkYWMyMTY3NGZkZTJmMzZmMGFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oTOX2hIEuGo4wg7MDUrLkwRTe8Mbq5vtw4wy3-XEWmg)

我多次尝试后，竟然成功解决了问题(两行热泪)，虽然这个tab对象依然使我困惑，将tab对象换成page对象可解决下载问题，虽然看起来不是很优雅
![ccc](https://github.com/g1879/DrissionPage/assets/143238423/61d84883-3dc4-41f5-bfe7-93a2ae5288a7)

**Comment by g1879** [comment]
因为是新弹出tab触发的下载，不能用原tab获取下载任务，可能new_tab参数有点问题，迟点会修复。
