### ISSUE TITLE
500chrome同时启动遇到错误

### ISSUE THREAD

**Issue by wjsw1781** [g1879/DrissionPage#242]
浏览器进程启动失败 错误：
timeout方法：
Page.getFrameTree参数：{'_timeout': 30}版本：
4.0.4.9运行时间：
7.134822594出现这个错误可能意味着程序有bug，
****
请把错误信息和重现方法告知作者，谢谢。报告网站：https://gitee.com/g1879/DrissionPage/issues
**![image](https://github.com/g1879/DrissionPage/assets/28215744/f30d8a2f-0abf-4a1a-b26b-97eb8e3311a9)**
****

**Comment by wjsw1781** [comment]
能否调整这个参数  即使调整成大一点 也行  我知道同时跑500 个chrome示例确实会有问题  但是我们这边爬取的量太大   cpu进群很大足够使用  我希望软件层面的超时成为瓶颈  希望大佬看下

**Comment by wjsw1781** [comment]
我希望软件层面的超时不应该成为瓶颈 希望大佬看下!
完整场景是50个chrome进程 每个开启60个tab页面  进行爬取亚马逊 并截图+html 用来给下游做多模态语义分析
总共10个这种机器
代理选型是国外vps动态拨号 总共两千台. 代理不是瓶颈  硬件也不是瓶颈 目前瓶颈卡在drissionpage对chrome的调度上了

**Comment by g1879** [comment]
4.0.4.9有点旧，先升级下。Timeout问题可能是浏览器的锅，dp没有对多浏览器进行调度。
