### ISSUE TITLE
求助！DP如何连接远程windows服务器上的chrome呢？

### ISSUE THREAD

**Issue by Zhu-HH** [g1879/DrissionPage#243]
我尝试更改ini配置文件的ip为服务器的IP，

window服务器上防火墙打开了9222端口
但显示无法连接

xx.xx.xx.xx:9222浏览器无法链接。
请确认：
1、该端口为浏览器
2、已添加'--remote-debugging-port=9222'启动项
3、用户文件夹没有和已打开的浏览器冲突
4、如为无界面系统，请添加'--headless=new'参数
5、如果是Linux系统，可能还要添加'--no-sandbox'启动参数
可使用ChromiumOptions设置端口和用户文件夹路径。

**Comment by Air-Zhuang** [comment]
同问
