### ISSUE TITLE
docker里启动失败

### ISSUE THREAD

**Issue by erquren** [g1879/DrissionPage#247]
![image](https://github.com/g1879/DrissionPage/assets/39297833/da632784-c689-4667-b8f6-158d9e725936)

我的期望：
能在docker里运行

我的操作：
docker pull 拉取了ubuntu2204的image，并创建了容器
更新软件源后apt install ./chrome的deb，安装了他缺少的库
通过miniconda安装了python环境py312，然后运行代码

from DrissionPage import ChromiumPage
from DrissionPage import ChromiumOptions
co = ChromiumOptions()
co.headless()  # 无头模式
co.set_argument('--no-sandbox')  # 无沙盒模式
print(1111)
page = ChromiumPage(co,timeout=3)
print(2222)

初始化的时候就G了，想问下是不是不支持在docker里进行运行

**Comment by yoursock** [comment]
是不是timeout设置的太短了，启动浏览器再加网络请求，3秒太短了吧。设置180试试

**Comment by erquren** [comment]
作者说 站不支持DOCKER

**Comment by g1879** [comment]
> 作者说 站不支持DOCKER

支持，有不少人在用，只是我还不会用docker。
