### ISSUE TITLE
缓存文件的问题

### ISSUE THREAD

**Issue by mrright2019** [g1879/DrissionPage#25]
操作系统： windows 10
python版本： 3.9

我使用有时效的代理，每次都开多个实例，发现C盘莫名其妙的满了，跟踪源码发现会创建缓存文件，user_data之类的数据，我主动设置user_data的位置后，发现还是会吃C盘空间，但是又找不到生成文件的地方。

**Comment by g1879** [comment]
这个问题我没有观察到，群里有人同时开100多个浏览器也没有反映这个问题，我迟点有空测试一下。

**Comment by mrright2019** [comment]
主动调用quit发现chrome经常没有杀死，又遇到过这种情况吗？请问怎么解决

**Comment by g1879** [comment]
> 主动调用quit发现chrome经常没有杀死，又遇到过这种情况吗？请问怎么解决

现在的版本quit()后要等2秒等它完全关闭，下个版本会解决这个问题。

**Comment by g1879** [comment]
最新版4.0.4.13优化了这个问题，可以试试。
