### ISSUE TITLE
drag 拖拽方法 过滑块的时候 

### ISSUE THREAD

**Issue by Alvinnlee** [g1879/DrissionPage#250]
有什么办法可以模拟人手一样先快再慢，有大佬可以指点一下代码吗

**Comment by Alvinnlee** [comment]
解决了

**Comment by miqitudou** [comment]
> 解决了

兄弟，你是咋解决的啦？
最近遇到一个滑块问题，我用这种方式去滑page('#aliyunCaptcha-sliding-slider').drag(360) 通过不了，他好像是要检测鼠标的轨迹？ 但是这种方法鼠标本身是不移动的
