### ISSUE TITLE
增加cookie，发现没有任何作用

### ISSUE THREAD

**Issue by pythonliuwei-root** [g1879/DrissionPage#255]
from DrissionPage import ChromiumPage

cookies = "name1=value1; name2=value2; path=/; domain=.example.com;"

page = ChromiumPage()
page.set.cookies(cookies)
print(page.cookies()) #[]

**Comment by chloe5685** [comment]
我也是

**Comment by g1879** [comment]
加上all_domains=True就能看到了。
