### ISSUE TITLE
集群部署遇到的pdf落盘问题

### ISSUE THREAD

**Issue by wjsw1781** [g1879/DrissionPage#257]
我这边在使用过程中  场景到达了2千万个html转换pdf的情况 这也就是意味着需要2000W个文件被创建   希望能想截图那样提供二进制流的模式  方便我直接接入对象存储  
目前对 io 压力非常大  已经成为了瓶颈

**Comment by wjsw1781** [comment]
虽然我可以边下边传  但始终是对io增加了压力  本来就是内存中可以完成的工作 这里实在是个矛盾的设计缺陷

**Comment by bluefire1999** [comment]
仔细看文档，有这功能。

**Comment by wjsw1781** [comment]
确实 确实  我的错  该罚
