### ISSUE TITLE
有个问题  下载路径有些文件无法控制下载位置

### ISSUE THREAD

**Issue by wjsw1781** [g1879/DrissionPage#258]
我已经设置了
        page.set.window.max()
        page.set.download_path(f'{pid_user_data_path}/download/')
![image](https://github.com/g1879/DrissionPage/assets/28215744/5f9d9703-2176-42d4-b189-b139aed48172)

可以发现文件确实被下载到这里了
![image](https://github.com/g1879/DrissionPage/assets/28215744/2b299aff-8656-47b2-b978-10191e597c50)

但是仍然有文件被下载到家目录下了
![image](https://github.com/g1879/DrissionPage/assets/28215744/6530876e-02a1-4d67-8b34-adf0b9ec7f11)

家目录一旦满了就会直接影响其他用户

**Comment by g1879** [comment]
没有具体环境没法排查。

**Comment by wjsw1781** [comment]
感觉就是chrome打开某些文件导致  这个没啥好办法 辛苦了
