### ISSUE TITLE
请问如何在控制台执行js，获取js返回的值？

### ISSUE THREAD

**Issue by Jesn** [g1879/DrissionPage#260]
![image](https://github.com/g1879/DrissionPage/assets/5728274/c2fdfc03-9e48-4a2d-afae-993a2011ba85)

例如: 我想在浏览器的控制台中 `return this.app.config.ath;`  并且返回对应的值，该如何处理？`page.run_js` 测试了下，好像无法获取到

**Comment by tanhh326** [comment]
```
page.run_js('return 0')
```

**Comment by g1879** [comment]
目前没有提供操作控制台的方法。
