### ISSUE TITLE
插件必须点击才能启用问题  

### ISSUE THREAD

**Issue by wjsw1781** [g1879/DrissionPage#262]
![image](https://github.com/g1879/DrissionPage/assets/28215744/75dc7316-bafa-4196-927b-ce20b576cf3a)

**Comment by wjsw1781** [comment]
https://microsoftedge.microsoft.com/addons/detail/cors-unblock/hkjklmhkbkdhlgnnfbbcihcajofmjgbh

这个是插件的安装路径

**Comment by wjsw1781** [comment]
终于解决了 
说下解决方案

首先一切功能都是基于chrome本身对插件运行时提供的功能而开发的   那么插件 形形色色的插件都是在这些功能上开发的出来的 所以我们需要的就是把这个开关打开而已

无奈的是这种需要点击才能开启的模式  不支持鼠标和ele进行选择点选 就是无法编程和感知
但是作者以前说过本质还是url  只要操作到这个url  就能进行真正意义上的点击进行开启了  没有url怎么办 那就改造这个插件

这里强烈推荐proxyomiga那个插件 他提供了popup.html的模式
参考那个popup.html  进行重新改写插件  从而实现开关效果
![image](https://github.com/g1879/DrissionPage/assets/28215744/9d7972d6-b057-46b3-9eec-b4404b53e51d)
![image](https://github.com/g1879/DrissionPage/assets/28215744/84f122df-eb5a-48b8-bfda-883106053ba9)



最终效果就是

**Comment by g1879** [comment]
不是很明白，意思是要改写要控制的插件才能实现调用吗？

**Comment by wjsw1781** [comment]
是的  那种需要点击才能开启的插件  本质上都会维护一个状态 这个插件https://microsoftedge.microsoft.com/addons/detail/cors-unblock/hkjklmhkbkdhlgnnfbbcihcajofmjgbh
就是把是否开启维护到了   chrome.storage.local中 enabled这个键值    如果一开始这个就是true那么插件的功能就开始发挥作用了
我就想直接改插件代码   发现没效果  后来参考proxyomega增加popup.html进行显式调用上面的代码  发现插件顺利开启了

**Comment by wjsw1781** [comment]
如果有可能的话   能把对插件图标的点击做成一种能力的话  我觉得肯定更好 ! 但是现阶段 我只能针对每个插件去定制化修改!
