### ISSUE TITLE
链式查找的问题

### ISSUE THREAD

**Issue by Lizc521** [g1879/DrissionPage#265]
![image](https://github.com/g1879/DrissionPage/assets/81208539/1c823599-72d3-4512-aa3d-156a76503acb)
![image](https://github.com/g1879/DrissionPage/assets/81208539/f63465f4-c6a8-4f9b-8804-fbff470495d5)

**Comment by Lizc521** [comment]
DrissionPage              4.0.4.24

**Comment by g1879** [comment]
没看出有什么问题，最好给个网址试试。
