### ISSUE TITLE
I want to run N number of browsers and then use them in parallel using threading, but when I call ChrmiumPage(), only 1 browser opens and all other threads do the same actions in it. How can I implement this?

### ISSUE THREAD

**Issue by Akshay-Shingala** [g1879/DrissionPage#267]
from DrissionPage import ChromiumPage
def open_browser(url):
    p = ChromiumPage()
    p.get("https://dexscreener.com/solana/5vfqvy8wjnawudgmjtuzypey8bjgsutzrnkhzsbv5viw")
    p.get(url)
urls = ["https://dexscreener.com/solana/5vfqvy8wjnawudgmjtuzypey8bjgsutzrnkhzsbv5viw"] * 3
threads = []
for i in range(len(urls)):
    t = threading.Thread(target=open_browser, args=(urls[i]))
    threads.append(t)
    t.start()
for t in threads:
     t.join()
     
## Many browsers are open but only one browser will search the URL all others are only open not take any action

**Comment by g1879** [comment]
看这里。
https://drissionpage.cn/demos/functions/create_browsers

**Comment by Akshay-Shingala** [comment]
thank you
