### ISSUE TITLE
Any way to capture websocket messages through network in devtools?

### ISSUE THREAD

**Issue by Mirac-ulous** [g1879/DrissionPage#27]
I'm using the latest version of DrissionPage and I cannot seem to find a function to record websocket messages, maybe there is a way to add chrome desired capabilities and record performance logs to see all the network logs but I cannot find anything regarding this in the documentation.

**Comment by g1879** [comment]
I have plans to implement this feature, but I don't think it will happen anytime soon.
see here:[http://g1879.gitee.io/drissionpagedocs/whatsnew/3_3/#_6](http://g1879.gitee.io/drissionpagedocs/whatsnew/3_3/#_6)

**Comment by Krylanc3lo** [comment]
I will have a look. 

@g1879, let us know if we can help

**Comment by g1879** [comment]
> I will have a look.
> 
> @g1879, let us know if we can help

Thanks. I'd love to have someone to develop with me. There are a lot of ideas that I don't have time for when I'm alone.
