### ISSUE TITLE
Drissionpage android?

### ISSUE THREAD

**Issue by riiiiiiki** [g1879/DrissionPage#270]
Actually, this is not a problem. I read somewhere that there is a library similar to DrissionPage but for Android. I wonder if it's true.

**Comment by Tlanhan** [comment]
Maybe not this library.
Author had plan for it.
https://github.com/g1879/DrissionPage/issues/22#issuecomment-1672899582

**Comment by g1879** [comment]
> Actually, this is not a problem. I read somewhere that there is a library similar to DrissionPage but for Android. I wonder if it's true.

可以发一下那个库的链接吗？
