### ISSUE TITLE
befour this i am using seleniumbase now i wan to use DrissionPage with proxy

### ISSUE THREAD

**Issue by Akshay-Shingala** [g1879/DrissionPage#275]
in seleniumbase i use in command python w.py --proxy=proxy=USERNAME:PASSWORD@pr.oxylabs.io:7777
in DrissionPage how can I set this ?

**Comment by akbarahmadshah** [comment]
You do this with ChromiumOptions.set_proxy(). Plus, username:pass isn't working at the moment so you must have your machine ip whitelisted and then pass the proxy string here with just IP:PORT.

**Comment by g1879** [comment]
目前要用这种代理需要使用插件，如SwitchyOmega。
