### ISSUE TITLE
点击下载按钮偶发出现no wait

### ISSUE THREAD

**Issue by wanghaisheng** [g1879/DrissionPage#276]
csv = tab.ele("CSV")
                filepath = f"keywordgap-{filename}-{filenames[idx]}.csv"
                logger.info(f"click to save csv:{keyword}--{idx} to file :{filepath}")

                mission = csv.click.to_download(
                    save_path="results",
                    rename=f"keywordgap-{filename}-{filenames[idx]}.csv",
                )
2024-06-23 22:57:38,412 - Line:719 - ERROR - it seems error :'bool' object has no attribute 'wait'

我不知道怎么定位和解决这个问题

**Comment by doom2030** [comment]
> ```
>             csv = tab.ele("CSV")
>             filepath = f"keywordgap-{filename}-{filenames[idx]}.csv"
>             logger.info(f"click to save csv:{keyword}--{idx} to file :{filepath}")
> 
>             mission = csv.click.to_download(
>                 save_path="results",
>                 rename=f"keywordgap-{filename}-{filenames[idx]}.csv",
>             )
> ```
> 
> 2024-06-23 22:57:38,412 - Line:719 - ERROR - it seems error :'bool' object has no attribute 'wait'
> 
> 我不知道怎么定位和解决这个问题
retry retry retry

**Comment by g1879** [comment]
有完整的报错信息吗？还有先升级试试。

**Comment by wanghaisheng** [comment]
我try catch Exceptions 只有这么一句 怎么拿到完整的报错信息@g1879

**Comment by doom2030** [comment]
> 有完整的报错信息吗？还有先升级试试。

mission 返回的是个false所以就报错了，页面上重试点击下载有可能成功，如果点击的元素不是button或者a标签，mission返回false的概率就比较大

**Comment by wanghaisheng** [comment]
我立马parent一下试试看 后续有没有问题 
@doom2030

**Comment by g1879** [comment]
就是等待不到下载任务，设置长一些的timeout和等待失败的处理。
