### ISSUE TITLE
'ChromiumPage' object has no attribute 'get_cookies'

### ISSUE THREAD

**Issue by Qs315490** [g1879/DrissionPage#279]
```python
page.download(image_url, work_path, f"{index}.jpg", file_exists="overwrite")
```
AttributeError: 'ChromiumPage' object has no attribute 'get_cookies'
使用 `Python 3.12`、`DrissionPage  4.0.5.3`

**Comment by g1879** [comment]
pip install DownloadKit --upgrade
升级一下这个就行。

**Comment by LPeng111** [comment]
升级无用。
`DownloadKit 2.0.2`、`DrissionPage  4.0.5.6`
