### ISSUE TITLE
No demos of code?

### ISSUE THREAD

**Issue by rcarvalho16** [g1879/DrissionPage#28]
I was looking for code examples, like navigating through html classes inside a webpage and clicking objects.
I can't find any examples that could help.

I used the code below to try and get all child divs from the one provided by xpath but it is not working

`    driver.get(link)

    while True:
        try:
            ele = driver.eles('xpath://*[@id="content"]/div/div[3]/div[2]')
            print(ele[0].child())
            break
        except:
            time.sleep(.1) 
`

**Comment by g1879** [comment]
Here are a few demos.
http://g1879.gitee.io/drissionpagedocs/demos/maoyan_TOP100/#_3
