### ISSUE TITLE
能否在元素进行查找，点击，输入，拖拽等很多交互的时候，加个remark，方便打印出调试的日志

### ISSUE THREAD

**Issue by xiao0502** [g1879/DrissionPage#280]
能否在元素进行查找，点击，输入，拖拽等很多交互的时候，加个remark，方便打印出调试的日志

**Comment by g1879** [comment]
remark有什么作用？

**Comment by xiao0502** [comment]
> remark有什么作用？

1. 在阅读代码的时候，通过remark的中文描述，知道这个元素获取了是为了干什么
2. 获取元素或者执行元素交互的函数打印remark，在程序执行的时候，知道跑到哪一步了

**Comment by g1879** [comment]
那这click()的时候自己写一下日志不就好了？
