### ISSUE TITLE
大规模部署心得=======以百亿页面渲染实际场景为例=======

### ISSUE THREAD

**Issue by wjsw1781** [g1879/DrissionPage#285]
具有标题党的嫌疑哈 但是实际情况是差不多的!

完整描述场景 这边有500亿个页面,你懂的就是来自外文cc以及国内自爬取的中文cc,现在需要把它渲染出来进行保存,目的是降维xpath提取工作,目标格式可以是图片  也可以是pdf!

 也就是 html--->png 或者html--->pdf   ,因为工程师不用写xpath提取了内容了,业界在ocr上积累以及pdf解析的积累 完全是模型的堆积,,效果和效率比人高出一大截 ,关键可以靠堆资源 优化算法的方式不断优化效果! 长远来看这是合理的 也是该投入的!

然后我就选型drissionpage来做集群化渲染工作,可想而知一堆坑要踩,  

1. 渲染进程不退出  ,
2. report和crash进程残留,
3. 页面中包含图片或者其他资源导致超时,
4. 很多是外网页面,加载过程就不会停止,导致转pdf和png出现阻塞,
5. 内存占用引起的内存泄露(掉头发),
6. 代理的配置,
7. vpn的搭建,
8. linux下centos和ubantu的差异性,
9. 无头模式带来的bug,
10. iframe嵌套导致的同源和不同源异常渲染(csp防护,就是原本这个页面放在iframe可以正常加载和看到内容,但是网站更新了防护规则,就不许这种加载 关键这种页面还很多 比如google csdn baidu这种大头   请看效果 )你猜那些网站做了防护    ![image](https://github.com/g1879/DrissionPage/assets/28215744/c0cf5dca-3275-4633-b788-d1a82459b643)
11. cpu 内存以及转换速度的效率之间的关系合理调控

先后嘞 我又总结了针对上述问题的解决方案,总结为几个大的方向
1.drissionpage对浏览器的拉起,关闭,操作------>就是生命周期,这个方面一大大规模部署很容易出现进程异常和卡顿问题,所以我放在一起讲,从本质触发,每个进程起来后肯定有一个port用来和它交互,cdp也正是借助ws和chrome在通信,一起问题的出现都是这个通道出现问题,超时,返回失败,连接断开,但是这个错误被作者包裹了,就导致我们看到一堆请联系作者的信息,换句话说堆栈只能看到drissionpage对cpd的抽象,而大部分开发者只会在群里问怎么实现***功能, 怎么**点不了, 怎么捕获不到**   你应当去跟一跟调用堆栈,到底哪里出现错误

2. 代理的切换和网络的选取,本质上是让浏览器使用某个代理去访问目标网站,作者也说了最好的方式是借助插件,但是它没给例子,我的亲身实测是 proxyomega 可以实现全流程代理切换, 运行时切换,没有后顾之忧! 怎么实现呢 你需要读懂这个插件开关逻辑,大致就是点击开启,设置代理!  难就难在无法点击插件区域,所以我的思路是直接强行大开插件的配置页面,这个页面就是你正常开启代理后点击切换的时候那个popup页面 ,后面就可以放飞自我了

3. 性能和效率的瓶颈问题   即使你采完了上述坑之后,你还是无法给公司代理效益,公司要的是产出,是量变代理的质变,此时你就该考虑大规模部署了 然后就遇到上述问题,群里有人想采用docker配合k8s来搞,我觉得不行,300G内存100核机器,你试试开400窗口基本上就会出现一堆超时,不管你怎么改进程数还是tab数,此时你再引入docker层,性能只会下降,本质是chrome太吃内存资源了   我提一个思路,也是我现在采用的方案   整体采用裸机+多进程+多tab页的方案,控制进程不变,和输入数据(我这里是100000个jsonl)形成逻辑上的对应就是 进程号和输入数据在逻辑上对应的 大白话就是  这份数据只会被某台机器的100号进程处理   此时我们不断修改tab个数,观察速度,成功率 失败率,你很快就能建立起一套进程 线程tab 处理速度以及cpu 内存之间的关系   然后就能批量部署,大批量跑了   做好线程池的维护和释放以及chrome的退出就行了

最终效果就是多机单节点10进程30tab线程情况下  每秒700页面处理, 成功率高达95% cpu和内存占用稳定在50%不影响观测和统计,
![企业微信截图_17195487076953](https://github.com/g1879/DrissionPage/assets/28215744/0b948a20-8b51-4a99-8ce7-1c2b33a7d184)

![企业微信截图_1719548741381](https://github.com/g1879/DrissionPage/assets/28215744/d98bd3b5-238e-4721-b593-b16e6adf5a51)

如果你也是搞这个大规模部署操作,不妨参考下,你也可以通过我的GitHub邮箱找到我

**Comment by LunacyZeus** [comment]
你这个拿来后台渲染页面性能应该不错。你这个类似渲染池吧，之前playwright有一套把纯js的网站渲染给爬虫用的。
但是如果你要大规模数据采集，有的网站要检测代理，环境，tls指纹，你这样采用一个chrome进程对应多个tabs的方案就会被检测。还是得一个一个开chrome，有的甚至需要指纹浏览器。
我目前是用阿里云的弹性扩容，python脚本设置自启，win启动的时候唤起指纹浏览器和hb脚本操作，从后台获取需要采集的脚本（网站），然后采集结束，回收示例。
几百台没啥问题，代理用的自建的拨号vps池，日志还是elk那一套，python这边报任何错都上传。其他的还没优化。🤣

**Comment by LunacyZeus** [comment]
`之前playwright有一套把纯js的网站渲染给爬虫用的。`
改正 爬虫=搜索引擎爬虫

**Comment by wjsw1781** [comment]
爬取的方案    这边采用的是 docker虚拟不同linux发行版+多版本chrome规避指纹,  代理也是自建拨号vps,  代理使用策略上保证代理用不被封或者封之前就更换,  没有日志系统  只看爬取速度  和成功率两个指标   走的是自己的集群 基本上能达到vps带宽瓶颈

**Comment by LunacyZeus** [comment]
> 爬取的方案 这边采用的是 docker虚拟不同linux发行版+多版本chrome规避指纹, 代理也是自建拨号vps, 代理使用策略上保证代理用不被封或者封之前就更换, 没有日志系统 只看爬取速度 和成功率两个指标 走的是自己的集群 基本上能达到vps带宽瓶颈

那还好，你这网站没那么严格，有的网站linux直接就给你封了，不认linux，因为正常用户不用linux，开无头也能把你检测出来。
最经典的creepjs，他判断你环境有问题给你打个风控分，然后有个轨迹流，记录你任何操作包括鼠标在元素上的移动，然后秋后算账。🤣

**Comment by kingname** [comment]
请问你是怎么解决内存泄漏的问题？

**Comment by wjsw1781** [comment]
> 请问你是怎么解决内存泄漏的问题？

单机多进程部署
通过进程和端口进行强绑定  防止一旦某个进程长时间卡住导致内存飙升  此时直接通过端口号强杀即刻  其他的方案我发现都没这个效果号
控制进程运行时间,无论怎么减低进程数 运行一段时间后 内存占用还是会上来,这就是chrome的缺点了,此时需要业务层面控制下
大致就这些
后期我们这边研究了下docker+k8s,直接基于容器进行生命周期管理更加高效  但是也有一些缺点,动不动就会报ws超时
