### ISSUE TITLE
浏览器启动设置里面集成插件操作问题

### ISSUE THREAD

**Issue by xiao0502** [g1879/DrissionPage#286]
在浏览器启动设置里面集成插件后，打开百度网页，插件会自动打开新的网页，并且弹出插件的弹窗

以okx钱包插件为例子

疑问点：
1. 为什么会自动打开okx的官网，并且弹出插件的小弹窗（打开是大概百度网页后的5秒左右，会自动打开okx的官网，并弹出插件小弹窗）
2. 我该如何操作插件小弹窗的页面交互？我能通过get_tabs()获取到三个tab，分别是百度网页，okx官网和插件小弹窗。我如何操作小弹窗里面的元素进行交互呢（小弹窗最后出现，默认是激活，我获取元素失败，通过激活标签页的两个函数后获取元素，也同样获取失败）。

**Comment by xiao0502** [comment]
<img width="1199" alt="image" src="https://github.com/g1879/DrissionPage/assets/20298200/183c6091-e514-4327-ba35-0736ff683033">

**Comment by g1879** [comment]
用get_tab()获取插件窗口对象和普通tab一样操作。自动打开官网是插件自己的行为。
