### ISSUE TITLE
set.local_storage() & clear_cache() ARE NOT WORKING

### ISSUE THREAD

**Issue by JOY6IX9INE** [g1879/DrissionPage#29]
Traceback (most recent call last):
  File "C:\Users\Joy\Desktop\Testing\main.py", line 48, in <module>
    page.set.local_storage(item='token', value='MTE0MDMyNTIzMTI4NjgxMjc2Mw.GJjSgo.XXXXXXXXXXXXX')
  File "C:\Python311\Lib\site-packages\DrissionPage\chromium_base.py", line 942, in local_storage
    return self._page.run_js_loaded(js, as_expr=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\DrissionPage\chromium_base.py", line 429, in run_js_loaded
    return run_js(self, script, as_expr, self.timeouts.script, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\DrissionPage\chromium_element.py", line 1283, in run_js
    raise JavaScriptError(f'\njavascript运行错误：\n{script}\n错误信息: \n{exceptionDetails}')
DrissionPage.errors.JavaScriptError:
javascript运行错误：
localStorage.setItem("token","MTE0MDMyNTIzMTI4NjgxMjc2Mw.GJjSgo.XXXXXXXXXXXX");
错误信息:
{'exceptionId': 4, 'text': 'Uncaught', 'lineNumber': 0, 'columnNumber': 0, 'scriptId': '44', 'exception': {'type': 'object', 'subtype': 'error', 'className': 'ReferenceError', 'description': 'ReferenceError: localStorage is not defined\n    at <anonymous>:1:1', 'objectId': '4185065306131059634.6.4'}}

**Comment by JOY6IX9INE** [comment]
I Am Getting Such Error While Using set.local_storage() And clear_cache()
What Is Issue And How Can I Fix It ??

**Comment by g1879** [comment]
This issue will be fixed in the next version, and can now be masked with a `try` statement.

**Comment by JOY6IX9INE** [comment]
When Are You Releasing The Next Version And Now How Can I do So ?? Or Can You Just Say How Can We Simply Run A Js Script In Browser page

**Comment by g1879** [comment]
use page.run_js()
