### ISSUE TITLE
当前目录为D:/Download等类似情况时，文件路径有问题

### ISSUE THREAD

**Issue by NICHX** [g1879/DrissionPage#291]
代码片段如下
` ques_img_url = ques_img.attr('src')
  ques_img_url = f'{ques_img_url}'
  page.download(ques_img_url, rf'.\imgs\{ID}\ques', rename=f'ques{i + 1}-title.png')
  page.wait(0.3, 0.6)
  doc.add_picture(rf'.\imgs\{ID}\ques\ques{i + 1}-title.png')`
预期情况图片下载到D:/Download/imgs/...
实际下载到了D:/ownload/imgs/...
![image](https://github.com/g1879/DrissionPage/assets/24547848/c5ff457c-df9a-4a8d-bb67-2ea92255abd8)

**Comment by g1879** [comment]
已修复，升级DownloadKit就行。
