### ISSUE TITLE
能用asyncio跑多个标签页吗

### ISSUE THREAD

**Issue by wanghaisheng** [g1879/DrissionPage#292]
for domain in domains:
            
            domain= f'https://radar.cloudflare.com/charts/WhoisPanel/fetch?domain={domain}'

            print(domain)

            proxy = None

            tab=browser.new_tab()

            page = browser.get_tab(tab)

            try:

                task = asyncio.create_task(
                    get_top(page,domain,  proxy, outfile)
                )
                # Ensure the semaphore is released even if the task fails
                # task.add_done_callback(lambda t: semaphore.release())
                # print('done', url)
                tasks.append(task)
                if len(tasks) >= concurrency:
                    # Wait for the current batch of tasks to complete
                    await asyncio.gather(*tasks)
                    tasks = []
我这样子它还是一个一个挨个启动

**Comment by doom2030** [comment]
> ```
>     for domain in domains:
>         
>         domain= f'https://radar.cloudflare.com/charts/WhoisPanel/fetch?domain={domain}'
> 
>         print(domain)
> 
>         proxy = None
> 
> 
>         tab=browser.new_tab()
> 
>         page = browser.get_tab(tab)
> 
> 
>         try:
> 
>             task = asyncio.create_task(
>                 get_top(page,domain,  proxy, outfile)
>             )
>             # Ensure the semaphore is released even if the task fails
>             # task.add_done_callback(lambda t: semaphore.release())
>             # print('done', url)
>             tasks.append(task)
>             if len(tasks) >= concurrency:
>                 # Wait for the current batch of tasks to complete
>                 await asyncio.gather(*tasks)
>                 tasks = []
> ```
> 
> 我这样子它还是一个一个挨个启动

不支持，目前最小只能是多线程，协程不支持
