### ISSUE TITLE
[CLOUDFLARE CF TURNSTILE DETECTION METHOD] when clicking on a element, the PointerEvent created is wrong

### ISSUE THREAD

**Issue by TheFalloutOf76** [g1879/DrissionPage#298]
# cloudflare is using this as a detection method

when clicking on a element with an event listener it triggers the function and sends it an argument [PointerEvent](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent). the values of [screenX](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/screenX) and [screenY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/screenY) in the PointerEvent is wrong.

## demo:
python code: 
```python
from DrissionPage import ChromiumPage, ChromiumOptions

co = ChromiumOptions()
co.auto_port()
page = ChromiumPage(co)

page.get("https://drissionpage.pages.dev/")

challengeButton = page.ele("tag:input")
challengeButton.click()
```

**Comment by mat-1** [comment]
Here's the relevant Chromium bug report: https://issues.chromium.org/issues/40280325

Amusingly, for me one "solution" is to zoom out so the page doesn't have a scroll bar.

**Comment by TheFalloutOf76** [comment]
> Here's the relevant Chromium bug report: https://issues.chromium.org/issues/40280325
> 
> Amusingly, for me one "solution" is to hide the scroll bar with `page.run_js("document.body.style.overflow = 'hidden'")` before clicking.

thank you so much, worked like a charm :)

**Comment by g1879** [comment]
> patching the event listener and changing the mouseevent screenx and screeny seems to have fixed it

How to do it?

**Comment by TheFalloutOf76** [comment]
by making a custom extension

**Comment by TheFalloutOf76** [comment]
https://github.com/TheFalloutOf76/drissionpage-cloudflare-fix

**Comment by TheFalloutOf76** [comment]
couldn't figure out how to inject code directly into iframe, so i made a extension to do it
```js
let oldAddEventListener = HTMLElement.prototype.addEventListener;

HTMLElement.prototype.addEventListener = addEventListener = function(type, callback) {
    function interceptor(event) {
        event.__defineGetter__('screenX',()=>1234)
        event.__defineGetter__('screenY',()=>567)
        console.log(event, event.screenX, event.screenY);
        callback.call(this, event);
    }
    if (type == 'click') {
        return oldAddEventListener.call(this, type, interceptor);
    }
    return oldAddEventListener.call(this, type, callback);
}
```

**Comment by g1879** [comment]
> couldn't figure out how to inject code directly into iframe, so i made a extension to do it
> 
> ```js
> let oldAddEventListener = HTMLElement.prototype.addEventListener;
> 
> HTMLElement.prototype.addEventListener = addEventListener = function(type, callback) {
>     function interceptor(event) {
>         event.__defineGetter__('screenX',()=>1234)
>         event.__defineGetter__('screenY',()=>567)
>         console.log(event, event.screenX, event.screenY);
>         callback.call(this, event);
>     }
>     if (type == 'click') {
>         return oldAddEventListener.call(this, type, interceptor);
>     }
>     return oldAddEventListener.call(this, type, callback);
> }
> ```

I tried, but it didn't work.

```python
from DrissionPage import *

co = ChromiumOptions()
co.add_extension('./turnstilePatch/')
p = ChromiumPage(co)
p.get('https://drissionpage.pages.dev/')
p('#detector').click()
```

**Comment by TheFalloutOf76** [comment]
It's for cloudflare turnstile only

**Comment by g1879** [comment]
> It's for cloudflare turnstile only

I changed 'matchs' in the plugin, but it didn't work either.

**Comment by TheFalloutOf76** [comment]
can you send a video recording?
it works fine for me

**Comment by TheFalloutOf76** [comment]
https://github.com/TheFalloutOf76/CDP-click-patch
slightly modified it, now it should work for all sites

**Comment by g1879** [comment]
> https://github.com/TheFalloutOf76/CDP-click-patch slightly modified it, now it should work for all sites

Thank you. I don't have a computer right now. I'll try later.

**Comment by TheFalloutOf76** [comment]
@g1879 hey, are you going to implement an in library fix?

**Comment by g1879** [comment]
Yes, and feel free to report back with more findings. g1879@qq.com.

**Comment by g1879** [comment]
> @g1879 hey, are you going to implement an in library fix?

Yes, and feel free to report back with more findings. g1879@qq.com.
