### ISSUE TITLE
启动浏览器失败

### ISSUE THREAD

**Issue by yxbbing123** [g1879/DrissionPage#3]
Starting ChromeDriver 109.0.5414.74 (e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
IPv6 port not available. Exiting...
[1675218601.404][SEVERE]: bind() returned an error: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 (0x2740)

**Comment by danny1879** [comment]
看看代码？是不是指定了dirver路径？应该指定chrome.exe的路径
