### ISSUE TITLE
无头模式和有头模式请求结果不一样

### ISSUE THREAD

**Issue by LPeng111** [g1879/DrissionPage#305]
网址：aHR0cHM6Ly9wYWltYWkuY2FhMTIzLm9yZy5jbi9wYWdlcy9ub3RpY2UvY2FyQ2hhbm5lbExpc3QuaHRtbA==
css：HTML > BODY > DIV:nth-of-type(2) > DIV:nth-of-type(1) > DIV:nth-of-type(1) > UL:nth-of-type(1) > LI > A:nth-of-type(1)

无头模式：
![image](https://github.com/user-attachments/assets/1c8a617e-bda1-414c-8473-d2fe32a5c45d)
有头模式：
![image](https://github.com/user-attachments/assets/e659e9bb-cced-40a8-82a5-680f2ee6f94f)

一开始以为是页面没有加载完成，增加了等待时间以及各种判定，结果还是一样，麻烦帮忙看看。

**Comment by g1879** [comment]
无头ua是有标识的，修改一下就行了。
