### ISSUE TITLE
Proxy auth support?

### ISSUE THREAD

**Issue by jewqrkqwrwq** [g1879/DrissionPage#31]
I was looking trough docs and i only saw proxy support without auth, is there a way to add them with auth? etc: ip:port@user:pass

**Comment by g1879** [comment]
In current version, this feature needs to be implemented with plug-ins.

**Comment by jewqrkqwrwq** [comment]
> In current version, this feature needs to be implemented with plug-ins.

can u link docs or example how to add extensions/plug ins? docs are hard for us non chinese :P

**Comment by g1879** [comment]
It's no example yet, I have been a little busy lately and haven't had time to write it. 
You can use SwitchyOmega.

**Comment by jewqrkqwrwq** [comment]
> It's no example yet, I have been a little busy lately and haven't had time to write it. You can use SwitchyOmega.

Gotcha, but can we control extension with drission? like changing proxies and such ?

**Comment by JasperSeling** [comment]
do.add_extension("путь к расширению c прокси")  и вы можете предварительно его создать
