### ISSUE TITLE
NoRectError: 该元素没有位置及大小。已经确认了页面中只有一个元素，并且用js来模拟点击可以。

### ISSUE THREAD

**Issue by wangzongming** [g1879/DrissionPage#311]
DrissionPage v4.0.5.6

在这种弹出层里面的按钮
![image](https://github.com/user-attachments/assets/dc88ea54-d4df-4e51-83f2-92a4f8190451)

49行处输出了找到的元素，输出也确实只有一个。
![image](https://github.com/user-attachments/assets/fd8abfd3-5c53-46f6-b7e4-6431a8895d3e)

![image](https://github.com/user-attachments/assets/5172a4af-9f0c-44f2-b8ae-7556903b5a6a)

实测在浏览器插件中，直接用方法就会好使，但是我试了 `code_img_alert[0].run_js('this.click();')` 也不行。
```
dom.click()
```

**Comment by wangzongming** [comment]
复现网址：https://jzsc.mohurd.gov.cn/data/company/detail?id=002105291241606274

**Comment by liuphillpotts** [comment]
dom.click(by_js=TURE)

**Comment by wangzongming** [comment]
用这个方法我也试过，不报错，但是点不到按钮。用js在浏览器控制台写模拟点击又可以。🤔

**Comment by g1879** [comment]
```python
from DrissionPage import ChromiumPage

p = ChromiumPage()
p.get('https://jzsc.mohurd.gov.cn/data/company/detail?id=002105291241606274')
e = p('重新验证')
e.wait.clickable()
e.click()
```
试过没问题。
