### ISSUE TITLE
@text()=ABC vs text:ABC 区别

### ISSUE THREAD

**Issue by zealinux** [g1879/DrissionPage#315]
想知道这两者的区别？
我有时 @text() click没有效果，我改成了 text: 就行了。

比如：<span>取消全部投放</span>

```
page.ele('@text()=取消全部投放').click()    # Not OK
page.ele('text:取消全部投放').click()           # OK
```

**Comment by XieJGit** [comment]
> 想知道这两者的区别？ 我有时 @text() click没有效果，我改成了 text: 就行了。
> 
> 比如：取消全部投放
> 
> ```
> page.ele('@text()=取消全部投放').click()    # Not OK
> page.ele('text:取消全部投放').click()           # OK
> ```

看这里面 https://drissionpage.cn/get_elements/syntax

tab.ele('@text()=第一行')  # 获取第一个文本**为“第一行”**的元素 ，即全匹配
ele = tab.ele('text:第二')  # 查找文本**包含“第二”**的元素 ，模糊匹配

**Comment by g1879** [comment]
区别在于`=`和`:`，不是`@text()`与`text`
