### ISSUE TITLE
功能请求 真心希望作者能给js_run加上返回值获取, 有些操作可能会依赖js运行来获取相应的返回值

### ISSUE THREAD

**Issue by 1273082756** [g1879/DrissionPage#319]
目前测试的情况下来看run_js返回的内容均是None

**Comment by MindBin633** [comment]
有些控制台可以获取的变量run_js获取不到，我也遇到这个问题了

**Comment by g1879** [comment]
js里加入return

**Comment by MindBin633** [comment]
![4c3209454d674640ed9fc3efe28c9cd1](https://github.com/user-attachments/assets/dbfb644f-7d42-43e8-ad73-4b70cfd5450e)
这个代码输出None
浏览器中这个是存在的
![8ed8388d8f5c355628e5a9d1fa4f4931](https://github.com/user-attachments/assets/4db15b0b-5b98-47b1-8375-2c0b963b7de2)


> js里加入return

**Comment by g1879** [comment]
发网址看看？

> ![4c3209454d674640ed9fc3efe28c9cd1](https://private-user-images.githubusercontent.com/53338920/365001735-dbfb644f-7d42-43e8-ad73-4b70cfd5450e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODk4MzAsIm5iZiI6MTcyNTU4OTUzMCwicGF0aCI6Ii81MzMzODkyMC8zNjUwMDE3MzUtZGJmYjY0NGYtN2Q0Mi00M2U4LWFkNzMtNGI3MGNmZDU0NTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAyMjUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZTZiNjMyOTlhZGYyZTMwZWUwZmY2MThmMDI4YjYyZWRmOGEwNzI5NTg5ZDlhMTVmNzA0Y2M3NzU3ZDY2MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nR3Bze1FuSHqVp5uoXxAEV6fAndFi6GKYweD2Wk-BWg) 这个代码输出None 浏览器中这个是存在的 ![8ed8388d8f5c355628e5a9d1fa4f4931](https://private-user-images.githubusercontent.com/53338920/365001809-4db15b0b-5b98-47b1-8375-2c0b963b7de2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODk4MzAsIm5iZiI6MTcyNTU4OTUzMCwicGF0aCI6Ii81MzMzODkyMC8zNjUwMDE4MDktNGRiMTViMGItNWI5OC00N2IxLTgzNzUtMmMwYjk2M2I3ZGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAyMjUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNDk4MWM5OTRmMmQwNTNhYzIwOGJlZWEzNjkyMWIyMTM0ZTIyMDAzZDdjOTVkMWJlZjgwMGJjMGEyMjkxZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yMDTw1N35LSYSXRX2GpXJBfk_AT_fohE5NiMmMuy_rU)
> 
> > js里加入return

网址发一下。

**Comment by MindBin633** [comment]
这个是购票界面需要登录的，&nbsp;


王斌
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月6日(星期五) 上午10:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [g1879/DrissionPage] 功能请求 真心希望作者能给js_run加上返回值获取, 有些操作可能会依赖js运行来获取相应的返回值 (Issue #319)














 
发网址看看？
  
 这个代码输出None 浏览器中这个是存在的 
  
js里加入return
   
网址发一下。
