### ISSUE TITLE
Remove DevTools message

### ISSUE THREAD

**Issue by Krylanc3lo** [g1879/DrissionPage#32]
Hello,

thanks a lot for the package, it is really amazing! Do you know how I could remove the "DevTools listening on ..." message and the return line just before ?

Thank you!

**Comment by g1879** [comment]
Sorry I didn't know that, there information doesn't appear on Windows, which I almost exclusively use.
If you find a solution, please let me know, I will write it in the document.

**Comment by Krylanc3lo** [comment]
ok thanks. it seems that we should use experimental_option:

options.add_experimental_option('excludeSwitches', ['enable-logging'])

I tried to add this option in configs.ini file but it does not work: 
experimental_options = {'prefs': {'excludeSwitches': ['enable-logging'], 'profile.default_content_settings.popups': 0, 'profile.default_content_setting_values': {'notifications': 2}}}

I will continue to investigate and let you know if I find anything.

Thanks again for your package and help!

**Comment by Krylanc3lo** [comment]
@g1879, here is the fix: we need to redirect the stdout in commons/browser.py when we launch chrome:
```

from subprocess import Popen, DEVNULL
...
def _run_browser(port, path: str, args) -> Popen:
    """创建chrome进程
    :param port: 端口号
    :param path: 浏览器地址
    :param args: 启动参数
    :return: 进程对象
    """
    p = Path(path)
    p = str(p / 'chrome') if p.is_dir() else str(path)
    arguments = [p, f'--remote-debugging-port={port}']
    arguments.extend(args)
    try:
        return Popen(arguments, shell=False, stdout=DEVNULL, stderr=DEVNULL)
    except FileNotFoundError:
        raise FileNotFoundError('未找到浏览器，请手动指定浏览器可执行文件路径。')
```

**Comment by g1879** [comment]
> , stdout=DEVNULL, stderr=DEVNULL

Thank you!
