### ISSUE TITLE
做了一个fastapi接口，但是长时间没有收到请求，与浏览器就会断开

### ISSUE THREAD

**Issue by econ1991lyj** [g1879/DrissionPage#323]
用的有头模式做了一个fastapi接口，外部请求调用页面html，但是如果长时间没有请求，chrome就会断开，
co = ChromiumOptions().headless(False)
co.set_argument('--no-sandbox').set_argument('--keep-alive')
这样设置--keep-alive有用吗？我试了好像不行，有别的方法能让fastapi启动后和chrome不会断开吗？

**Comment by g1879** [comment]
浏览器有个省电设置，我也没试过，你试试看有没有用？回来说说。
