### ISSUE TITLE
最新测试版4.1.0.0b19遗漏WebPageTab

### ISSUE THREAD

**Issue by 19caiji** [g1879/DrissionPage#324]
**item.py遗漏webpagetab,会影响使用了type升级到4.1.0.0的项目**
![1](https://github.com/user-attachments/assets/ec2f8668-2f0f-4638-bf9a-e87cf6663966)
**参照__init__.py文件修正如下**
![2](https://github.com/user-attachments/assets/38db9952-92d4-473b-ad10-6707f2908384)

**Comment by g1879** [comment]
收到，谢谢。
