### ISSUE TITLE
working fine in windows, but not working in ubuntu

### ISSUE THREAD

**Issue by gyanjoshi** [g1879/DrissionPage#33]
I used this package to bypass cloudflare challenge. This has been working in windows. But, same code does not work in ubuntu with desktop gui.

**Comment by Krylanc3lo** [comment]
Do you have an error message ? I am using ubuntu and no issue on my side

**Comment by g1879** [comment]
I have tested it on several Linux systems, all of which work fine, including ubuntu, centos, UOS, NeoKylin. However, Linux is not my usual system, please send me the detailed error information.

**Comment by gyanjoshi** [comment]
there was some issue with my configuration. It works fine in ubuntu as well.

**Comment by Keramatfar** [comment]
> I have tested it on several Linux systems, all of which work fine, including ubuntu, centos, UOS, Kylin. However, Linux is not my usual system, please send me the detailed error information.

Does it works in non headless mode?

**Comment by g1879** [comment]
> > I have tested it on several Linux systems, all of which work fine, including ubuntu, centos, UOS, Kylin. However, Linux is not my usual system, please send me the detailed error information.
> 
> Does it work in non headless mode?

可以的。
