### ISSUE TITLE
获取的cookies 好像不是很全

### ISSUE THREAD

**Issue by jiupinjiandingshi** [g1879/DrissionPage#334]
我在使用数据包监听的时候 ，发现request.cookies的数据 ，和我从网页上拿下来的cookies少了不少字段 能看看是什么问题吗？

**Comment by g1879** [comment]
麻烦发一下重现代码

**Comment by jiupinjiandingshi** [comment]
就是正常的listen.wait() 获取request的cookies ,发现跟我用谷歌插件拿出来的cookies 不是太对的上

**Comment by RanZiXuan** [comment]
影响正常流程吗

**Comment by g1879** [comment]
在request.extra_info.headers，下个版本会整合到headers。
