### ISSUE TITLE
DrissionPage 已安装，但是 提示 No module named 'drissionpage'，怎么办？

### ISSUE THREAD

**Issue by GOgo8Go** [g1879/DrissionPage#338]
Python 3.12.1
DrissionPage 4.0.5.6
pip install DrissionPage --upgrade
Requirement already satisfied (4.0.5.6)

但是会报错：from drissionpage import DrissionPage
ModuleNotFoundError: No module named 'drissionpage'

请问，该怎么解决？

**Comment by the-best-richer** [comment]
我也遇见了，重装了几次都没解决，楼主有解决方案吗，求助
