### ISSUE TITLE
how to click on an item of list !

### ISSUE THREAD

**Issue by amirwwe619** [g1879/DrissionPage#34]
Assuming the following `<select>` elements, the following example is based on this:
```
<select id='s' multiple>
    <option value='value1'>text1</option>
    <option value='value2'>text2</option>
    <option value='value3'>text3</option>
</select>
```

how do I **click** on _text2_? I don't want to use `select()` function , I need to click on it so some ajax data would load afterward

**Comment by Krylanc3lo** [comment]
you could use

```
ele = page.ele(text2)
ele.click()
```

**Comment by danny1879** [comment]
`<option>` elements cannot be clicked, but `select()` method triggers `onChange` action.
If this doesn't work, I'll try the `onClick` action in the next version.

**Comment by g1879** [comment]
`<option>` elements cannot be clicked, but `select()` method triggers `onChange` action.
If this doesn't work, I'll try the `onClick` action in the next version.

**Comment by taghizad3h** [comment]
I have the same issue. In my case, if a normal user clicks on an option, a network call is triggered which updates the options available in following lists. But using `select` nothing happens.

**Comment by g1879** [comment]
> I have the same issue. In my case, if a normal user clicks on an option, a network call is triggered which updates the options available in following lists. But using `select` nothing happens.

Can you send me the web address for testing? Every website I've ever used has been triggered correctly.

**Comment by amirwwe619** [comment]
![image](https://github.com/g1879/DrissionPage/assets/15013429/ce71f083-7794-40fe-9f26-7aaf37f663c6)

url: [https://it-ir-appointment.visametric.com/en](url)
path: `[Study button] -> ●  OK ->  ● Iran ->[Get Appointment button] `

**Comment by g1879** [comment]
> > > I have the same issue. In my case, if a normal user clicks on an option, a network call is triggered which updates the options available in following lists. But using `select` nothing happens.
> > 
> > 
> > Can you send me the web address for testing? Every website I've ever used has been triggered correctly.
> 
> ![image](https://user-images.githubusercontent.com/15013429/264589722-ce71f083-7794-40fe-9f26-7aaf37f663c6.png)
> 
> url: https://it-ir-appointment.visametric.com/en path: `[Study button] -> ● OK -> ● Iran ->[Get Appointment button] `

"Sorry, you have been blocked
You are unable to access visametric.com"

I can't access the site.

**Comment by atropates** [comment]
> > > > I have the same issue. In my case, if a normal user clicks on an option, a network call is triggered which updates the options available in following lists. But using `select` nothing happens.
> > > 
> > > 
> > > Can you send me the web address for testing? Every website I've ever used has been triggered correctly.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/15013429/264589722-ce71f083-7794-40fe-9f26-7aaf37f663c6.png)
> > url: https://it-ir-appointment.visametric.com/en path: `[Study button] -> ● OK -> ● Iran ->[Get Appointment button] `
> 
> "Sorry, you have been blocked You are unable to access visametric.com"
> 
> I can't access the site.

The site is : https://ir-appointment.visametric.com/en

**Comment by g1879** [comment]
> > > > > I have the same issue. In my case, if a normal user clicks on an option, a network call is triggered which updates the options available in following lists. But using `select` nothing happens.
> > > > 
> > > > 
> > > > Can you send me the web address for testing? Every website I've ever used has been triggered correctly.
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/15013429/264589722-ce71f083-7794-40fe-9f26-7aaf37f663c6.png)
> > > url: https://it-ir-appointment.visametric.com/en path: `[Study button] -> ● OK -> ● Iran ->[Get Appointment button] `
> > 
> > 
> > "Sorry, you have been blocked You are unable to access visametric.com"
> > I can't access the site.
> 
> The correct site url is : https://ir-appointment.visametric.com/en

我这里还是不能使用这个网站。

**Comment by atropates** [comment]
> 
would you mind give me a way of communication so that I can easily stay in touch with you : like Telegram, what's app or anything ?

**Comment by atropates** [comment]
> > > > > > I have the same issue. In my case, if a normal user clicks on an option, a network call is triggered which updates the options available in following lists. But using `select` nothing happens.
> > > > > 
> > > > > 
> > > > > Can you send me the web address for testing? Every website I've ever used has been triggered correctly.
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/15013429/264589722-ce71f083-7794-40fe-9f26-7aaf37f663c6.png)
> > > > url: https://it-ir-appointment.visametric.com/en path: `[Study button] -> ● OK -> ● Iran ->[Get Appointment button] `
> > > 
> > > 
> > > "Sorry, you have been blocked You are unable to access visametric.com"
> > > I can't access the site.
> > 
> > 
> > The correct site url is : https://ir-appointment.visametric.com/en
> 
> 我这里还是不能使用这个网站。

>would you mind give me a way of communication so that I can easily stay in touch with you : like Telegram, what's app or anything ?

**Comment by atropates** [comment]
> > > > > > I have the same issue. In my case, if a normal user clicks on an option, a network call is triggered which updates the options available in following lists. But using `select` nothing happens.
> > > > > 
> > > > > 
> > > > > Can you send me the web address for testing? Every website I've ever used has been triggered correctly.
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/15013429/264589722-ce71f083-7794-40fe-9f26-7aaf37f663c6.png)
> > > > url: https://it-ir-appointment.visametric.com/en path: `[Study button] -> ● OK -> ● Iran ->[Get Appointment button] `
> > > 
> > > 
> > > "Sorry, you have been blocked You are unable to access visametric.com"
> > > I can't access the site.
> > 
> > 
> > The correct site url is : https://ir-appointment.visametric.com/en
> 
> 我这里还是不能使用这个网站。

would you mind give me a way of communication so that I can easily stay in touch with you : like Telegram, what's app or anything ?

**Comment by atropates** [comment]
> > > > > > > > I have the same issue. In my case, if a normal user clicks on an option, a network call is triggered which updates the options available in following lists. But using `select` nothing happens.
> > > > > > > 
> > > > > > > 
> > > > > > > Can you send me the web address for testing? Every website I've ever used has been triggered correctly.
> > > > > > 
> > > > > > 
> > > > > > ![image](https://user-images.githubusercontent.com/15013429/264589722-ce71f083-7794-40fe-9f26-7aaf37f663c6.png)
> > > > > > url: https://it-ir-appointment.visametric.com/en path: `[Study button] -> ● OK -> ● Iran ->[Get Appointment button] `
> > > > > 
> > > > > 
> > > > > "Sorry, you have been blocked You are unable to access visametric.com"
> > > > > I can't access the site.
> > > > 
> > > > 
> > > > The correct site url is : https://ir-appointment.visametric.com/en
> > > 
> > > 
> > > 我这里还是不能使用这个网站。
> > 
> > 
> > would you mind give me a way of communication so that I can easily stay in touch with you : like Telegram, what's app or anything ?
> 
> I only have WeChat.

do you have an email ?

**Comment by g1879** [comment]
> > > > > > > > > I have the same issue. In my case, if a normal user clicks on an option, a network call is triggered which updates the options available in following lists. But using `select` nothing happens.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Can you send me the web address for testing? Every website I've ever used has been triggered correctly.
> > > > > > > 
> > > > > > > 
> > > > > > > ![image](https://user-images.githubusercontent.com/15013429/264589722-ce71f083-7794-40fe-9f26-7aaf37f663c6.png)
> > > > > > > url: https://it-ir-appointment.visametric.com/en path: `[Study button] -> ● OK -> ● Iran ->[Get Appointment button] `
> > > > > > 
> > > > > > 
> > > > > > "Sorry, you have been blocked You are unable to access visametric.com"
> > > > > > I can't access the site.
> > > > > 
> > > > > 
> > > > > The correct site url is : https://ir-appointment.visametric.com/en
> > > > 
> > > > 
> > > > 我这里还是不能使用这个网站。
> > > 
> > > 
> > > would you mind give me a way of communication so that I can easily stay in touch with you : like Telegram, what's app or anything ?
> > 
> > 
> > I only have WeChat.
> 
> do you have an email ?

g1879@qq.com

**Comment by g1879** [comment]
最新版应该已经解决这个问题。
