### ISSUE TITLE
能否出一些run_js的案例

### ISSUE THREAD

**Issue by pengjinfu** [g1879/DrissionPage#340]
在puppeter或者playwright中者有以下功能https://pptr.nodejs.cn/api/puppeteer.page.evaluate：
class Page {
  evaluate<
    Params extends unknown[],
    Func extends EvaluateFunc<Params> = EvaluateFunc<Params>,
  >(
    pageFunction: Func | string,
    ...args: Params
  ): Promise<Awaited<ReturnType<Func>>>;
}

这里能否出一个跟这个一样的功能，我发现同样的js语句：
# 执行JavaScript
encrypt_params = await page.evaluate('([url, data]) => window._webmsxyw(url, data)', [url, data])
local_storage = await page.evaluate('() => window.localStorage')
在用run_js行不通，哪怕是把列表改为参数，这边能否多出一些这样的实际案例让我使用，谢谢

**Comment by g1879** [comment]
事情太多，一个人写忙不过来，欢迎投稿。
