### ISSUE TITLE
Remove .pyi files for direct type hinting in .py files

### ISSUE THREAD

**Issue by KJHJason** [g1879/DrissionPage#342]
When developing, I often find myself going to the definition of the various functions/methods to look at the argument types and the logic behind them especially when debugging.
However, due to the types being defined in the stub files (.pyi), I often have to manually find the .pyi and the function/method name for the argument types. 
 
For instance, finding the type hinting for the arguments in `set_argument` from the definition file.
![image](https://github.com/user-attachments/assets/67179295-61dc-471d-b20c-25f170bd12ee)
![image](https://github.com/user-attachments/assets/3fc69a11-c932-415f-8afe-0d0ad068b919)

Instead, you should put the type hinting in the same file instead of separating it into .pyi files like the image below;
![image](https://github.com/user-attachments/assets/be736f34-9502-4bf0-ba0a-cfc63c5f21c2)

I don't see why you would use stub files (.pyi) over using type hinting directly in the same file but would like to hear your thoughts on this matter.

Edit:
I could make a pull request to close this issue but knowing how frequently the source code on Gitee changes, there will be lots of merge conflicts and headaches.

**Comment by g1879** [comment]
pyi的好处非常多，甚至有些功能如果不用pyi是无法实现的。很早之前的版本就是在代码中用类型注解，一些功能写不下去了才知道了pyi的好处。

**Comment by g1879** [comment]
比如说，我可以写不同语言版本的pyi文件，你需要英语的注释，就安装英语版本的pyi文件。你的IDE就会用英文给你提示api用法。
如果你有兴趣，欢迎做一些翻译，写出英文版的pyi文件。
