### ISSUE TITLE
无痕模式打开浏览器，新建不了无痕标签？

### ISSUE THREAD

**Issue by IamMagicSu** [g1879/DrissionPage#345]
下面的代码会先打开一个无痕的浏览器，然后再打开一个非无痕的浏览器并新建标签链接到百度，
我试着写了new_tab(new_window=False)，但没有用，依然会打开两个浏览器，无法在无痕模式浏览器上新建标签：

from DrissionPage import WebPage,ChromiumOptions

co = ChromiumOptions()
co.incognito(on_off=True)#无痕模式
page = WebPage(chromium_options=co)
tab = page.new_tab()  # 新建标签页，获取标签页对象
tab.get('https://www.baidu.com')  # 用标签页对象对标签页进行操作

**Comment by y1ck3z** [comment]
I made it and here is the solution:
(by the way, it seems that new_window does not work....

```python
co = ChromiumOptions()
co.set_argument('--incognito')
page = WebPage(chromium_options=co)
tab_1 = page.new_tab(new_window=False, new_context=True)
tab_2 = page.new_tab(new_window=False, new_context=True)

**Comment by g1879** [comment]
4.1.0.0b21已修复无痕时new_tab()问题

**Comment by althon** [comment]
DrissionPage v4.1.0.9 这个问题仍然存在，没有修复
