### ISSUE TITLE
DrissionPage how to bypass cloudflare in headless mode

### ISSUE THREAD

**Issue by Nlkita357** [g1879/DrissionPage#358]
Trying to bypass cloudflare in headless mode.
Trying:
`chrome_options = ChromiumOptions()
chrome_options.set_user('User')
chrome_options.headless(True)
chrome_options.set_argument('--start-maximized')
chrome_options.set_argument('--blink-settings=imagesEnabled', 'false')

driver = ChromiumPage(chrome_options)

tab = Actions(self.driver)
tab = Actions(driver)
tab.key_down(Keys.TAB)
tab.key_up(Keys.TAB)
tab.key_down(Keys.SPACE)
tab.key_up(Keys.SPACE)
`
Any answers would be appreciated!

**Comment by g1879** [comment]
修改一下ua，无头下ua是带Headless文本的。
