### ISSUE TITLE
timeout参数不生效

### ISSUE THREAD

**Issue by zhouwenjun-hub** [g1879/DrissionPage#364]
1. 遇到了什么问题？什么场景下出现的？如何重现？

SessionPage访问url时的timeout参数不生效，我设置超时时间是1秒，但是6秒才从get(url)方法返回

2. 请附上代码和报错信息（如有）

```python
import time

from DrissionPage._pages.session_page import SessionPage

start = time.time()
page = SessionPage(timeout=1)
page.get("https://baijiahao.baidu.com/s?id=1808687806920443820&wfr=spider&for=pc", timeout=1)
if page.html:
    print(page.ele("tag:body").text)
else:
    print("html为空")
print(f'cost {time.time() - start}')
```
![image](https://github.com/user-attachments/assets/1af12985-bace-4a29-89cf-a8a144dec2dc)

3. DrissionPage、浏览器、python版本号是多少？

DrissionPage 4.0.5.6

**Comment by g1879** [comment]
默认重试3次，每次间隔2秒而已。可以设置的。
