### ISSUE TITLE
page.get_tab()返回值问题

### ISSUE THREAD

**Issue by nocrabs** [g1879/DrissionPage#369]
page.get_tab() 实际返回了当前激活的tab, 跟文档描述(当所有参数都为None时，获取 Page 对象控制的标签页的 Tab 对象。)有差异
drissionpage版本: 4.0.4.23
代码:
h1 = page.get_tab()
new_h = page.new_tab(url='about:blank')
h2 = page.get_tab() #h2获取到的tab值是new_h
page.ele('xpath://div') #调用page操作, 响应的tab却是h1

照我的理解, h2的返回值或者其它时间调用page.get_tab()应该始终返回h1才对

**Comment by g1879** [comment]
4.1新增了Chromium对象，对tab的管理更清晰，推荐升级。
https://drissionpage.cn/features/4.1
