### ISSUE TITLE
Coding specification

### ISSUE THREAD

**Issue by wu-clan** [g1879/DrissionPage#37]
Add mypy, pre-commit, ruff, black support

**Comment by wu-clan** [comment]
Abandon use of pyi, built-in type hints

**Comment by g1879** [comment]
很久以前的版本是用代码注解的，后来改成pyi了。
pyi让代码更简洁，感觉运行效率也高点。
最重要的是，可以很好解决循环导入的问题，用代码注解这个问题无解。
除此之外，pyi还有些更灵活的用法。
至于代码规范，pycharm默认的就很够用了。
