### ISSUE TITLE
龙蜥os上DrissionPage不能和cv2或者ddddocr同时导入，一起导入就报错

### ISSUE THREAD

**Issue by Acheng97** [g1879/DrissionPage#375]
x86_64版本的Anolis OS8.9GA，python是3.11，ddddocr是ddddocr-py311
即使不使用cv2或者ddddocr，他们仨个包同时导入也会报错，注释掉他们三个其中一个就没事，以下是示例代码：
import cv2
import ddddocr
from DrissionPage import ChromiumPage
from DrissionPage._configs.chromium_options import ChromiumOptions

co = ChromiumOptions().auto_port()
co.set_argument('--no-sandbox')

page = ChromiumPage(addr_or_opts=co)
page.get('https://www.baidu.com')
time.sleep(1)
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/73579a6d-cd88-4254-837d-4766dd6bfb22">

**Comment by g1879** [comment]
没用过龙蜥os，但是一起导入就导致连接浏览器失败，这个感觉有点不合理。会不会是别的原因。

**Comment by Acheng97** [comment]
> 没用过龙蜥os，但是一起导入就导致连接浏览器失败，这个感觉有点不合理。会不会是别的原因。

那就有可能是他操作系统的问题了
