### ISSUE TITLE
使用无头模式 会弹出一个白窗 alttab选不了这个白窗

### ISSUE THREAD

**Issue by Lyk1a** [g1879/DrissionPage#381]
code 如下
def perform_task(port):
    co = ChromiumOptions().headless(True)
    co.set_local_port(port)
    co.set_argument("--headless")
    page = ChromiumPage(co)
    page.get(URL)
    time.sleep(5)
    page(MES_BOX).input("你好")
    page(SUBMIT_BTN).click()
    page(MES_BOX).clear()
    page(MES_BOX).input("你好2")
    page(SUBMIT_BTN).click()
    print(port)
    page.quit()

def main():
    threads = []
    for i in range(1):
        thread = Thread(target=perform_task, args=(i + 8000,))
        thread.start()
        threads.append(thread)

    for thread in threads:
        thread.join()

if __name__ == "__main__":
    main()
    
![1726578728676](https://github.com/user-attachments/assets/c3ac1189-dc6f-4efb-822d-66649c630cc7)

**Comment by misakawa1996** [comment]
我也遇到了一样的问题，无头模式会弹出白窗，怎么解决呀

**Comment by Vella-17** [comment]
+1 无头模式会弹出白窗 不知道有没有什么影响

**Comment by HGSheldonCao** [comment]
co.set_argument('--headless=new') 用这个

**Comment by hero3020** [comment]
chromium version 問題, 下載新版本的chromium, 再把browser_path 指過去

**Comment by ChthollyWn** [comment]
> chromium version 問題, 下載新版本的chromium, 再把browser_path 指過去

下载了最新版本，path也指向了，还是出现了这个问题，Chrome版本为129.0.6668.59

**Comment by Tangylin** [comment]
有办法解决吗，更新到最新版chrome 129.0.6668.59就有白屏问题了，之前128版本是正常的

**Comment by ChthollyWn** [comment]
应该是chrome.exe的问题导致出现的白窗，我更换了edge后问题解决，如果有办法在不更换浏览器的情况下解决该问题，请踢我下
![image](https://github.com/user-attachments/assets/2cfc6277-8c15-4884-8d83-4e2c64de5e6e)

**Comment by HGSheldonCao** [comment]
没有人试试这个吗 co.set_argument('--headless=new')

**Comment by Tangylin** [comment]
> 没有人试试这个吗 co.set_argument('--headless=new')

试过了，没用，还是白屏，换到128就正常

**Comment by hero3020** [comment]
> > chromium version 問題, 下載新版本的chromium, 再把browser_path 指過去
> 
> 下载了最新版本，path也指向了，还是出现了这个问题，Chrome版本为129.0.6668.59

就是129有問題呀, 128, 130 就没問題
130 我是用chromium 不是用chrome的
