### ISSUE TITLE
切换tab多好用啊，为啥要删掉，现在get_tab一点都不好用，我怎么切换到main_tab呢？？？很无语！搞了好久！

### ISSUE THREAD

**Issue by lonely1215225** [g1879/DrissionPage#382]
<img width="879" alt="image" src="https://github.com/user-attachments/assets/802a07ad-44d2-4bac-9482-6e0d814d0316">

**Comment by g1879** [comment]
https://drissionpage.cn/features/4#%EF%B8%8F-%E6%A0%87%E7%AD%BE%E9%A1%B5%E7%AE%A1%E7%90%86
https://drissionpage.cn/tutorials/functions/tabs
详见这里。
