### ISSUE TITLE
How to convert Selenium driver.execute_script("document.getElementById('gpay-button-online-api-id').click()") to  DrissionPage

### ISSUE THREAD

**Issue by tunght2406** [g1879/DrissionPage#386]
![image](https://github.com/user-attachments/assets/f41bcb2a-5f67-4222-9dd6-0077d8b8d056)
![image](https://github.com/user-attachments/assets/8355cb83-fb4f-4bd0-8f86-6fb07dcd076a)

I tried using the command below but it didn't work:
btn_buy = page.ele("#gpay-button-online-api-id").click()
page.run_js("document.getElementById('gpay-button-online-api-id').click()")

I opened Devtool as shown in the picture and executed the command below and it was successful:
"document.getElementById('gpay-button-online-api-id').click()"

So can I use the javascript command: "document.getElementById('gpay-button-online-api-id').click()" for drissionpage? Please help

**Comment by wxhzhwxhzh** [comment]
page.run_js("document.getElementById('gpay-button-online-api-id').click()")

**Comment by tunght2406** [comment]
> page.run_js("document.getElementById('gpay-button-online-api-id').click()")

I used it but not working

**Comment by g1879** [comment]
可能只是按钮没有准备好，等1秒再点击试试。
