### ISSUE TITLE
該如何多屬性匹配類別?

### ISSUE THREAD

**Issue by OtwakO** [g1879/DrissionPage#390]
Example: `<div class="meta-data pages"> test content </div>`

試過都不行:  
- ("class:meta-data pages")
- (@@class:meta-data@@class:pages")
- ("class:meta-data@@class:pages")
- ("class='meta-data pages'")

**Comment by wxhzhwxhzh** [comment]
t:div@@class=meta-data pages

**Comment by wxhzhwxhzh** [comment]
ele('@Class=meta-data pages')

**Comment by OtwakO** [comment]
前面加了html tag之後就可以了，我之後試試@Class=meta-data pages可不可以，一定要加tag的話有點不太方便

**Comment by g1879** [comment]
https://drissionpage.cn/browser_control/get_elements/syntax
语法的文档在这里。
