### ISSUE TITLE
page对象的download方法运行失败/page instance's download method crashed...

### ISSUE THREAD

**Issue by Schweik7** [g1879/DrissionPage#40]
```py
from DrissionPage import WebPage
page=WebPage()
fileurl="https://images.unsplash.com/photo-1519810755548-39cd217da494?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDV8fE5pZ2h0JTIwc2t5fGVufDB8fDB8fHww&w=1000&q=80"
page.download(
    file_url=fileurl,
    file_exists="overwrite",
    show_msg=True,
)
```
会报如下的错：
![image](https://github.com/g1879/DrissionPage/assets/25610011/f0e4f0d1-06f4-4eb3-bc56-b9b5a91ae25d)

**Comment by g1879** [comment]
不奇怪，`download()`是基于requests的，如果下载地址要求headers，要自己在参数中带上。

**Comment by Schweik7** [comment]
谢谢！没有仔细看代码，以为是通过浏览器下载的。另外，我想调用图片元素img_ele的save方法，为什么img_ele的prop("currentSrc")属性会为空呢？图片在浏览器是加载出来了的

**Comment by Schweik7** [comment]
大约有20%的图片没有这个currentSrc属性，导致使用download()下载图片

**Comment by g1879** [comment]
> 大约有20%的图片没有这个currentSrc属性，导致使用download()下载图片

要看看才知道。网址发下？
