### ISSUE TITLE
How to avoid Cloudflare challenge page ?

### ISSUE THREAD

**Issue by gyanjoshi** [g1879/DrissionPage#41]
I am using DrissonPage to crawl through a job posting site. I have used ChromePage() object and ChromiumOptions() object to build page object to manipulate the page elements. I haved added some code to click on the Cloudflare challenge. Initially, it was successfully passing the challenge. However, Now, this is not working, It can not identify the checkbox input and click on it ? Do anyone have faced similar issues ?

**Comment by g1879** [comment]
Try this. Wait a few seconds before clicking.​https://youtu.be/TCRcRXszhhU

**Comment by gyanjoshi** [comment]
> Try this. Wait a few seconds before clicking.​https://youtu.be/TCRcRXszhhU

Hats off for this quick solution. It worked.
