### ISSUE TITLE
AttributeError: 'ChromiumPage' object has no attribute 'get_cookies'

### ISSUE THREAD

**Issue by solomsk** [g1879/DrissionPage#410]
完整代码：

```
from DrissionPage import ChromiumPage

page = ChromiumPage()

page.get('https://www.baidu.com')
print(page.get_cookies())

page.quit()
```

报错：
Traceback (most recent call last):
  File "D:\自动读取CK\自动获取ck.py", line 8, in <module>
    print(page.get_cookies())
          ^^^^^^^^^^^^^^^^
AttributeError: 'ChromiumPage' object has no attribute 'get_cookies'

我的追查：
我试过 #279 提到的方法 ： pip install DownloadKit --upgrade 依然没用，还是报这个错。

运行环境：
Python 3.12.7
DrissionPage       4.1.0.8
DownloadKit        2.0.4

**Comment by g1879** [comment]
改成page.cookies()
