### ISSUE TITLE
打开浏览器冲突时，会打开一个空白的浏览器

### ISSUE THREAD

**Issue by songge8** [g1879/DrissionPage#42]
复现场景：相同用户文件夹，不同端口。启动第二个浏览器时，虽然会抛出异常DrissionPage.errors.BrowserConnectError，但是仍然会启动一个空白的浏览器窗口，且无法通过page.quit()关闭

**Comment by g1879** [comment]
每个浏览器进程都要独立端口和文件夹，不能同时共用。把用户文件夹复制一个用吧。

**Comment by songge8** [comment]
由于要复用同一个用户的浏览数据，但又不好判断上一个进程是否结束，所以只能这样设置。有没有办法在冲突的时候直接就不启动新的窗口或者关闭打开的新窗口呢？

**Comment by g1879** [comment]
现在的版本quit()后要等2秒才能正真结束浏览器，下个版本会修复这个问题。

**Comment by songge8** [comment]
问题不在这，使用page.quit()尝试关闭新打开的空白窗口时会报错UnboundLocalError: local variable 'page' referenced before assignment

**Comment by g1879** [comment]
我意思是前一个浏览器关闭时等几秒。不然接管不了，自然不能对空白窗口quit()了。

**Comment by g1879** [comment]
最新版3.2.32已发布，quit()可自动浏览器进程完全关闭。
