### ISSUE TITLE
是否考虑增加拦截修改网络请求功能。

### ISSUE THREAD

**Issue by 519544044** [g1879/DrissionPage#428]
现在只能拿到请求之后得网络数据,能不能请求发起之前进行拦截，篡改。

**Comment by g1879** [comment]
不考虑这个功能。

**Comment by 519544044** [comment]
这个网络拦截的功能对于提高性能还是很重要。 比如 图片 字体 样式 直接返回空字符。或者替换成本地文件。可以节省内存和节省流量，提高并发速度
