### ISSUE TITLE
new_tab() has not timeout parameter, please add it

### ISSUE THREAD

**Issue by ilyazanuda** [g1879/DrissionPage#433]
![image](https://github.com/user-attachments/assets/dff9fa16-ff5a-4595-92ca-23440b2f9d23)

I think the new_tab function should have a timeout attribute because the get function has it.

![image](https://github.com/user-attachments/assets/e3c8460d-e75a-470b-ae60-34bc211bb1ef)

**Comment by g1879** [comment]
get()还有retry和interval参数，如果都加上去我觉得会很臃肿。如果需要设置的话，可以先new_tab()，再get()。
