### ISSUE TITLE
Get Request Header with Listener

### ISSUE THREAD

**Issue by sandrocods** [g1879/DrissionPage#44]
I use a 

from DrissionPage.tools import Listener

listener =Listener(9222)  # 创建监听器，监听9222端口的浏览器
listener.set_targets('JobSearchResult.aspx')  # 设置需要监听的url

listener.listen(count=10)  # 开始监听，接收到10条目标url的请求后停止

for i in listener.steps():
    print(i.body)  # 打印实时打印监听到的内容

listener.stop()  #停止监听

but can only get response header, how to get a request header ?

**Comment by g1879** [comment]
下一个版本将会解决这个问题。现在的版本使用`wait.data_packets()`也可以。
