### ISSUE TITLE
Cloudflare blocked my request

### ISSUE THREAD

**Issue by gyanjoshi** [g1879/DrissionPage#45]
![image](https://github.com/g1879/DrissionPage/assets/33371786/7d9a717d-7312-4cb5-b3af-072b1e507569)

After few days of successfully avoiding the cloudflare challenge page using this package, Now, I am getting this error page as response. Seems like, host site has temporarily blocked my IP address itself, though I am using proxy server to rotate IP address with each request. is there any solution to this ? Suggestions are appreciated.

**Comment by g1879** [comment]
我没有其它方法。

**Comment by juhacz** [comment]
> Seems like, host site has temporarily blocked my IP address itself, though I am using proxy server to rotate IP address with each request. is there any solution to this ? Suggestions are appreciated.

How do you change the proxy server of your choice for each request?

**Comment by HkerVit** [comment]
> ![image](https://user-images.githubusercontent.com/33371786/266472827-7d9a717d-7312-4cb5-b3af-072b1e507569.png)
> 
> After few days of successfully avoiding the cloudflare challenge page using this package, Now, I am getting this error page as response. Seems like, host site has temporarily blocked my IP address itself, though I am using proxy server to rotate IP address with each request. is there any solution to this ? Suggestions are appreciated.

you request very fast?
