### ISSUE TITLE
我要在一个不同域名的iframe中包含的textarea输入怎么搞呢？

### ISSUE THREAD

**Issue by tomyu168** [g1879/DrissionPage#461]
根据官方说明如果<iframe>跟当前标签页是不同域名的，不能使用页面对象直接查找其中元素，只能先获取其ChromiumFrame元素对象，再在这个对象中查找。
这似乎无法实现输入？

**Comment by pythonlw** [comment]
可以先获取iframe对象再进行操作，看以下两个案例
//&nsp;
shadow_root>iframe 
def run1():
&nsp;&nsp;&nsp;&nsp;co1 = ChromiumOptions().set_paths(local_port=19315)
&nsp;&nsp;&nsp;&nsp;browser = ChromiumPage(addr_or_opts=co1)
&nsp;&nsp;&nsp;&nsp;browser.set.window.show() # 显示页面
&nsp;&nsp;&nsp;&nsp;page = browser.latest_tab
&nsp;&nsp;&nsp;&nsp;page.get('https://www.metin2pserver.info/vote-guabi.htm')
&nsp;&nsp;&nsp;&nsp;time.sleep(2)
&nsp;&nsp;&nsp;&nsp;flag = False
&nsp;&nsp;&nsp;&nsp;for i in range(15):
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;disabled = page.run_js('''var temp= document.querySelector('div#RGIpp2'); if(temp){return true}else{return false}''')
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;print('disabled:', disabled)
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;if disabled:
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;flag = True
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;break
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;else:
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;time.sleep(1)
&nsp;&nsp;&nsp;&nsp;if flag:
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;div_shadow = page.ele('xpath://div[@id="RGIpp2"]/div/div')
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;iframe = div_shadow.shadow_root.get_frame('t:iframe')
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;shadow_root1 = iframe.ele('xpath://body')
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;print(shadow_root1.inner_html)
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;checkbox = shadow_root1.shadow_root.ele('xpath://input[@type="checkbox"]')
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;print(checkbox.text)
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;checkbox.click()

general iframe
def run2():
&nsp;&nsp;&nsp;&nsp;co1 = ChromiumOptions().set_paths(local_port=19315)
&nsp;&nsp;&nsp;&nsp;browser = ChromiumPage(addr_or_opts=co1)
&nsp;&nsp;&nsp;&nsp;browser.set.window.show() # show tab
&nsp;&nsp;&nsp;&nsp;page = browser.latest_tab
&nsp;&nsp;&nsp;&nsp;page.get('https://drissionpage.cn/demos/iframe_diff_domain.html')
&nsp;&nsp;&nsp;&nsp;time.sleep(2)
&nsp;&nsp;&nsp;&nsp;iframe = page.get_frame('t:iframe')
&nsp;&nsp;&nsp;&nsp;print(iframe)
&nsp;&nsp;&nsp;&nsp;a_tag = iframe.ele('xpath://a[@id="ariaTipText"]')
&nsp;&nsp;&nsp;&nsp;print(a_tag.attrs)

**Comment by pythonlw** [comment]
//&nsp;
可以先获取iframe对象再进行操作，看以下两个案例
shadow_root>iframe 
`def run1():
&nsp;&nsp;&nsp;&nsp;co1 = ChromiumOptions().set_paths(local_port=19315)
&nsp;&nsp;&nsp;&nsp;browser = ChromiumPage(addr_or_opts=co1)
&nsp;&nsp;&nsp;&nsp;browser.set.window.show() # 显示页面
&nsp;&nsp;&nsp;&nsp;page = browser.latest_tab
&nsp;&nsp;&nsp;&nsp;page.get('https://www.metin2pserver.info/vote-guabi.htm')
&nsp;&nsp;&nsp;&nsp;time.sleep(2)
&nsp;&nsp;&nsp;&nsp;flag = False
&nsp;&nsp;&nsp;&nsp;for i in range(15):
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;disabled = page.run_js('''var temp= document.querySelector('div#RGIpp2'); if(temp){return true}else{return false}''')
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;print('disabled:', disabled)
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;if disabled:
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;flag = True
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;break
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;else:
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;time.sleep(1)
&nsp;&nsp;&nsp;&nsp;if flag:
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;div_shadow = page.ele('xpath://div[@id="RGIpp2"]/div/div')
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;iframe = div_shadow.shadow_root.get_frame('t:iframe')
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;shadow_root1 = iframe.ele('xpath://body')
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;print(shadow_root1.inner_html)
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;checkbox = shadow_root1.shadow_root.ele('xpath://input[@type="checkbox"]')
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;print(checkbox.text)
&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;&nsp;checkbox.click()

general iframe
def run2():
&nsp;&nsp;&nsp;&nsp;co1 = ChromiumOptions().set_paths(local_port=19315)
&nsp;&nsp;&nsp;&nsp;browser = ChromiumPage(addr_or_opts=co1)
&nsp;&nsp;&nsp;&nsp;browser.set.window.show() # show tab
&nsp;&nsp;&nsp;&nsp;page = browser.latest_tab
&nsp;&nsp;&nsp;&nsp;page.get('https://drissionpage.cn/demos/iframe_diff_domain.html')
&nsp;&nsp;&nsp;&nsp;time.sleep(2)
&nsp;&nsp;&nsp;&nsp;iframe = page.get_frame('t:iframe')
&nsp;&nsp;&nsp;&nsp;print(iframe)
&nsp;&nsp;&nsp;&nsp;a_tag = iframe.ele('xpath://a[@id="ariaTipText"]')
&nsp;&nsp;&nsp;&nsp;print(a_tag.attrs)`

**Comment by pythonlw** [comment]
//&nbsp;
可以先获取iframe对象再进行操作，看以下两个案例
shadow_root>iframe 
def run1():
&nbsp;&nbsp;&nbsp;&nbsp;co1 = ChromiumOptions().set_paths(local_port=19315)
&nbsp;&nbsp;&nbsp;&nbsp;browser = ChromiumPage(addr_or_opts=co1)
&nbsp;&nbsp;&nbsp;&nbsp;browser.set.window.show() # 显示页面
&nbsp;&nbsp;&nbsp;&nbsp;page = browser.latest_tab
&nbsp;&nbsp;&nbsp;&nbsp;page.get('https://www.metin2pserver.info/vote-guabi.htm')
&nbsp;&nbsp;&nbsp;&nbsp;time.sleep(2)
&nbsp;&nbsp;&nbsp;&nbsp;flag = False
&nbsp;&nbsp;&nbsp;&nbsp;for i in range(15):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;disabled = page.run_js('''var temp= document.querySelector('div#RGIpp2'); if(temp){return true}else{return false}''')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print('disabled:', disabled)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if disabled:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;flag = True
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;time.sleep(1)
&nbsp;&nbsp;&nbsp;&nbsp;if flag:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;div_shadow = page.ele('xpath://div[@id="RGIpp2"]/div/div')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iframe = div_shadow.shadow_root.get_frame('t:iframe')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;shadow_root1 = iframe.ele('xpath://body')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(shadow_root1.inner_html)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;checkbox = shadow_root1.shadow_root.ele('xpath://input[@type="checkbox"]')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(checkbox.text)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;checkbox.click()

general iframe
def run2():
&nbsp;&nbsp;&nbsp;&nbsp;co1 = ChromiumOptions().set_paths(local_port=19315)
&nbsp;&nbsp;&nbsp;&nbsp;browser = ChromiumPage(addr_or_opts=co1)
&nbsp;&nbsp;&nbsp;&nbsp;browser.set.window.show() # show tab
&nbsp;&nbsp;&nbsp;&nbsp;page = browser.latest_tab
&nbsp;&nbsp;&nbsp;&nbsp;page.get('https://drissionpage.cn/demos/iframe_diff_domain.html')
&nbsp;&nbsp;&nbsp;&nbsp;time.sleep(2)
&nbsp;&nbsp;&nbsp;&nbsp;iframe = page.get_frame('t:iframe')
&nbsp;&nbsp;&nbsp;&nbsp;print(iframe)
&nbsp;&nbsp;&nbsp;&nbsp;a_tag = iframe.ele('xpath://a[@id="ariaTipText"]')
&nbsp;&nbsp;&nbsp;&nbsp;print(a_tag.attrs)
