### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by 6958194** [g1879/DrissionPage#463]
报错DrissionPage.errors.PageDisconnectedError: 与页面的连接已断开。怎么解决

**Comment by g1879** [comment]
要看具体情况，tab关闭了或者iframe没了就断开了呗。

**Comment by babug123** [comment]
> 要看具体情况，tab关闭了或者iframe没了就断开了呗。

目前发现win11系统进入睡眠 或 休眠模式，重新唤醒后，之前持续运行中的代码好像必然触发【DrissionPage.errors.PageDisconnectedError: 与页面的连接已断开。】报错。
