### ISSUE TITLE
在Linux下使用 SessionPage.get 读取本地文件，当传入绝对路径时，会导致读取失败

### ISSUE THREAD

**Issue by TobisLee** [g1879/DrissionPage#464]
当使用下面代码读取本地文件时，会读取失败：
```python
page = SessionPage()
page.get('/home/tlss/a.html')
```

原因是`lstrip`并不是精准匹配，它会将url开头的`/`去掉，变成`home/tlss/a.html`，导致绝对路径无法被识别
https://github.com/g1879/DrissionPage/blob/ea7d539fbe16471cb37d9e98cdc066999dd37638/DrissionPage/_pages/session_page.py#L116

解决方法：
可以尝试使用`url.replace('file:///', '', 1)`替换

**Comment by g1879** [comment]
谢谢，下个版本修复。
