### ISSUE TITLE
Don't close the browser when script is exited

### ISSUE THREAD

**Issue by taghizad3h** [g1879/DrissionPage#47]
Hi
When running from windows if I close the script the browser continues it's life.
But in ubuntu and osx the browser closes as soon as the script is closed.
How can I avoid that?

**Comment by g1879** [comment]
我不清楚。我主要用Windows。
但其他人使用MAC和Linux是可以保留浏览器的。我使用过UOS版本的Linux，是可以保留的。

**Comment by g1879** [comment]
你是否使用VS Code？有人说VS Code会关闭浏览器。可以先启动浏览器，再用程序接管就可以了。
