### ISSUE TITLE
How using move_to()

### ISSUE THREAD

**Issue by HkerVit** [g1879/DrissionPage#49]
I have captcha. and i have posstion X, Y in image Captcha
how to move_to X, Y in image captcha and click?
tks for support

**Comment by g1879** [comment]
http://g1879.gitee.io/drissionpagedocs/ChromiumPage/action_chains/

**Comment by HkerVit** [comment]
i want to click posstion (x,y) inside image.
It is captcha. I and want to click to solve captchas
how to using move_to details?

**Comment by g1879** [comment]
用动作链就可以，详细用法看这里：
http://g1879.gitee.io/drissionpagedocs/ChromiumPage/action_chains/
