### ISSUE TITLE
想知道作者使用了那些黑科技可以减少指纹的暴露，防止网页探测为bot

### ISSUE THREAD

**Issue by fireinrain** [g1879/DrissionPage#5]
你好作者大大，我本人用java写了个项目，之前可以运行，但是后面cloudflare升级 导致可以检测出我使用了selenium
页面一直在cf的页面刷新 没法进入到后面的逻辑。 所以我想知道这个库用了什么黑科技手段 可以消除selenium指纹

**Comment by g1879** [comment]
我这个不是用selenium的，自己实现的底层，所以没有webdriver特征，测试过5s盾和专门的检测网站，都能轻松过。

**Comment by mrright2019** [comment]
> 我这个不是用selenium的，自己实现的底层，所以没有webdriver特征，测试过5s盾和专门的检测网站，都能轻松过。

作者不要告诉楼上的,告诉他 他就给搞指纹检测了!

**Comment by ZhanglinX233** [comment]
....

**Comment by ZhanglinX233** [comment]
主要是现在已经不行了
