### ISSUE TITLE
Potential issue - 117.0.5938.63 + headless.

### ISSUE THREAD

**Issue by Gait0fH3ll** [g1879/DrissionPage#50]
Ever since I updated chrome (auto-update) to:117.0.5938.6

Headless mode is completely broken, as soon as I remove the headless flag, all is working fine.

This may just be an issue on my end, but if somebody could test, would be great.

I will close this issue if I manage to somehow figure out the issue.

**Comment by g1879** [comment]
我升级到117.0.5938.6，测试以下代码，工作正常。

```python
from DrissionPage import ChromiumPage, ChromiumOptions

co = ChromiumOptions().set_headless()
p = ChromiumPage(co)
p.get('https://www.baidu.com')
print(p.title)
p.quit()
```

**Comment by Gait0fH3ll** [comment]
Your test code doesn't work for me either, strange.

    options.set_headless(True)
(1 browser) = 88% CPU usage

   #options.set_headless(True)
(1 browser) = 0.2% CPU usage.

I think the latest version of chrome is just broken.

It was working perfectly before the auto update lol

**Comment by Gait0fH3ll** [comment]
Downgrading chrome fixed the issue, so I will make as resolved
