### ISSUE TITLE
DrissionPage.errors.JavaScriptError:  javascript运行错误：

### ISSUE THREAD

**Issue by Wenboli11** [g1879/DrissionPage#51]
code:
 a = page.run_js(script='''var t=Object.keys(window).find(function(name) {
        return name.startsWith("flashvars_")
    });window[t].mediaDefinitions[0].videoUrl;

File "C:\Users\23613\Desktop\autobot\mybot\main.py", line 53, in send_video
    a = page.run_js(script='''var t=Object.keys(window).find(function(name) {
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\DrissionPage\chromium_base.py", line 419, in run_js
    return run_js(self, script, as_expr, self.timeouts.script, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\DrissionPage\chromium_element.py", line 1281, in run_js
    raise JavaScriptError(f'\njavascript运行错误：\n{script}\n错误信息: \n{exceptionDetails}')
DrissionPage.errors.JavaScriptError: 
javascript运行错误：
var t=Object.keys(window).find(function(name) {
        return name.startsWith("flashvars_")
    });window[t].mediaDefinitions[0].videoUrl;
    
错误信息: 
{'exceptionId': 2, 'text': 'Uncaught', 'lineNumber': 2, 'columnNumber': 17, 'scriptId': '588', 'exception': {'type': 'object', 'subtype': 'error', 'className': 'TypeError', 'description': "TypeError: Cannot read properties of undefined (reading 'mediaDefinitions')\n    at <anonymous>:3:18", 'objectId': '4368662864434784137.9.3'}}
请问这是什么错误，怎样解决？

**Comment by g1879** [comment]
先确定网页正常再执行js呗。

**Comment by g1879** [comment]
> > 先确定网页正常再执行js呗。
> 
> 网页能打开，但是结构变了，跟之前的不一样了

那针对网页情况写。
