### ISSUE TITLE
建議把 run_js 的 code 從 chromium_element 搬到 BaseElement, 讓 SessionElement 也可以執行 run_js

### ISSUE THREAD

**Issue by max32002** [g1879/DrissionPage#55]
前因是, ChromiumElement 的反應時間太長, 改用 SessionElement 雖可以解決 select element, 雖然找到 element,  但無法執行 run_js 中的 argument[0].

還有要建議 run_js 的 isinstance 除了 ChromiumElement, ChromiumShadowRoot 之外, 也可以允許 SessionElement.

**Comment by g1879** [comment]
SessionElement快就是因为它是静态的啊。
