### ISSUE TITLE
import ChromiumPage Error

### ISSUE THREAD

**Issue by smallma** [g1879/DrissionPage#57]
Hello, 

After installed DrissionPage, I just executed the flowing command on MacOS, the console show a error as below image. Please help me out. Thanks.

from DrissionPage import ChromiumPage

<img width="1118" alt="image" src="https://github.com/g1879/DrissionPage/assets/429250/2e34b5a4-4dc8-4d73-916c-d876cb15bdcd">

**Comment by g1879** [comment]
看上去是lxml库没安装好的原因？
另外，我建议你的项目文件夹不要命名为DrissionPage，可能会发生冲突。

**Comment by smallma** [comment]
後來找到是 python 3.9 造成問題, 降到 python 3.7 就正常了

但是 form button submit 有遇到無法點擊問題

也發生常常點擊導頁後會找不到元件

**Comment by g1879** [comment]
我3.6之后每个版本都用过，都是可以的，可能是你的环境lxml没安装好。

**Comment by max32002** [comment]
Windows + Python 3.9 路過. 測試功能都正常.
