### ISSUE TITLE
 許願 DrissionPage 的 ele() 的反應速度追上 selenium 的 find element.

### ISSUE THREAD

**Issue by max32002** [g1879/DrissionPage#59]
目前在DrissionPage v3.2.31  的 d模式下, 每找一個節點, 和 selenium 相比, 慢很多, 希望有朝一日, 可以變快.

**Comment by g1879** [comment]
> 目前在DrissionPage v3.2.31 的 d模式下, 每找一個節點, 和 selenium 相比, 慢很多, 希望有朝一日, 可以變快.

慢是因为没找到元素在等待。设置一下timeout参数试试。

**Comment by max32002** [comment]
👍

g1879 ***@***.***> 於 2023年9月25日 週一 下午12:41 寫道：
