### ISSUE TITLE
启动浏览器失败

### ISSUE THREAD

**Issue by s348268281** [g1879/DrissionPage#6]
按文档设置了chrome.exe路径并添加配置成功，执行
page = ChromiumPage()
page.get('http://g1879.gitee.io/DrissionPageDocs')
报错PermissionError: [WinError 5] 拒绝访问。
查看python.exe右键属性安全里所有权限都勾上了，chrome.exe权限也都勾上了，还是失败

**Comment by g1879** [comment]
看看设置代码？

**Comment by yangweijie** [comment]
mac 版启动不了

**Comment by g1879** [comment]
> mac 版启动不了

报什么错？应该是没设置好，很多人用mac

**Comment by yangweijie** [comment]
![image](https://user-images.githubusercontent.com/1614114/233215737-70d6c779-e08f-4df4-8da4-5e34ae6fa7e2.png)
![image](https://user-images.githubusercontent.com/1614114/233215849-e79fea7f-8427-4581-90ea-1c4e625864a1.png)
浏览器是存在的，改了777权限也不行。同样写法 win下可以打开。

**Comment by g1879** [comment]
![](http://g1879.gitee.io/drissionpagedocs/imgs/find_browser_path.png)

用这个方法找浏览器路径试试，群里不少人用MAC，这个方法应该可以的。

**Comment by yangweijie** [comment]
> ![](https://camo.githubusercontent.com/193d1c70776c1b374c81bee14dbaa592a412902c908edf3ccbe20cc12ba93609/687474703a2f2f67313837392e67697465652e696f2f6472697373696f6e70616765646f63732f696d67732f66696e645f62726f777365725f706174682e706e67)
> 
> 用这个方法找浏览器路径试试，群里不少人用MAC，这个方法应该可以的。

我图中就是这么来的。 要不你拉我进群

![image](https://user-images.githubusercontent.com/1614114/233756900-cdb56665-1048-4eb3-8972-39a2150c9937.png)

**Comment by g1879** [comment]
嗯……我没有mac，我看其他人都是设置了这个路径就行了

**Comment by g1879** [comment]
> > ![](https://camo.githubusercontent.com/193d1c70776c1b374c81bee14dbaa592a412902c908edf3ccbe20cc12ba93609/687474703a2f2f67313837392e67697465652e696f2f6472697373696f6e70616765646f63732f696d67732f66696e645f62726f777365725f706174682e706e67)
> > 用这个方法找浏览器路径试试，群里不少人用MAC，这个方法应该可以的。
> 
> 我图中就是这么来的。 要不你拉我进群
> 
> ![image](https://user-images.githubusercontent.com/1614114/233756900-cdb56665-1048-4eb3-8972-39a2150c9937.png)

QQ群号：897838127

**Comment by moriweiji** [comment]
centos7 上也启动不了样

**Comment by CcgKaneki** [comment]
Mac版要打开Chrome浏览器app包内容，路径写这个
ChromiumOptions().set_paths(browser_path='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')
<img width="610" alt="image" src="https://github.com/g1879/DrissionPage/assets/17875330/47d46a3c-7951-41a1-b0c2-4a6f3ce5a7f9">
<img width="818" alt="image" src="https://github.com/g1879/DrissionPage/assets/17875330/b6249692-0ca9-4c3c-8765-565be15c6127">

**Comment by Cthousand** [comment]
@CcgKaneki 不错,你的方式是可行的,但我还碰到了这个错误
<img width="1278" alt="image" src="https://github.com/g1879/DrissionPage/assets/102720782/4e449695-266e-4427-80aa-ece3cdf78ad3">
有懂行的大佬支个招吗?

**Comment by Cthousand** [comment]
> @CcgKaneki 不错,你的方式是可行的,但我还碰到了这个错误 <img alt="image" width="1278" src="https://user-images.githubusercontent.com/102720782/244602205-4e449695-266e-4427-80aa-ece3cdf78ad3.png"> 有懂行的大佬支个招吗?
已经解决了,我自己的问题,是update被禁用了打开了就行
