### ISSUE TITLE
Working fine with GUI mode, but request is blocked with headless mode

### ISSUE THREAD

**Issue by gyanjoshi** [g1879/DrissionPage#60]
After few days of crawling using, headless mode, request is completely blocked by the Cloudflare. But same crawler with removing the headless mode works fine.

**Comment by 79102576** [comment]
Some websites will detect whether the browser is in an active state.

**Comment by g1879** [comment]
3.2.34版可以在最小化的时候也能正常运作了。
另外，无头的ua是不一样的，网站会根据这个屏蔽，自己修改就行了。
