### ISSUE TITLE
How to confirm the confirmation pop-up box

### ISSUE THREAD

**Issue by ginipropro** [g1879/DrissionPage#61]
How to confirm the confirmation pop-up box

**Comment by HkerVit** [comment]
yes how to?

**Comment by g1879** [comment]
pop-up box是指哪个？

**Comment by HkerVit** [comment]
In selenium:
try:
        alert = driver.switch_to.alert
        text = alert.text
        # print(text)
        alert.accept()
except Exception as err:

And how to mod to DrissionPage to fix it?

**Comment by bluefire1999** [comment]
page.handle_alert()
