### ISSUE TITLE
我点击一个按钮后自动是打开一个新的页面如何操作新的页面对象啊

### ISSUE THREAD

**Issue by wejudging** [g1879/DrissionPage#64]
page.ele('tag:a@tx()=验证电子邮件').click()
自动是新建一个新的页面，原有页面还在
如何操作新的页面对象啊

**Comment by wejudging** [comment]
print(page.tabs_count)
输出还是1
但是我是打开了2个页面

**Comment by g1879** [comment]
搜get_tab()

**Comment by killerddd3** [comment]
用get_tab可以吗？我也遇到了同样的问题，我试了get_tab无法获取到新打开的窗口
