### ISSUE TITLE
今天使用踩了一个坑,关于函数签名的帮助信息不正确的问题

### ISSUE THREAD

**Issue by 178me** [g1879/DrissionPage#65]
![image](https://github.com/g1879/DrissionPage/assets/50314769/4121e6dc-d3cc-4cc9-ab6e-96672c715a74)
上面的 args 说是在script中的占位符是 argument[0] ... 
实际上是 arguements[0] ,少了一个s,调了半天,搜官网例子才发现

**Comment by g1879** [comment]
谢谢，我修复一下。
