### ISSUE TITLE
Can any1 translate this to english 💀

### ISSUE THREAD

**Issue by duylmaoxd** [g1879/DrissionPage#66]

**Comment by g1879** [comment]
我也希望有人帮我做这件事。

**Comment by yemreak** [comment]
Why dont u use chatGPT to translate content? @g1879

**Comment by g1879** [comment]
> Why dont u use chatGPT to translate content? @g1879

因为文档经常修改，我需要一个一键翻译所有markdown文档的工具，需要能够保存文档格式和相对路径。
如果没有这个工具，无法保证两种语言的文档是一致的。
而且我对使用的文档框架还不是很熟悉，还不知道要怎么做。
希望有人能够帮助我。
