### ISSUE TITLE
it doesn't work when specify the proxy, how to do this

### ISSUE THREAD

**Issue by cxchen100** [g1879/DrissionPage#68]
code like this:
"""
from DrissionPage import ChromiumPage, WebPage, ChromiumOptions
from DrissionPage.easy_set import set_paths, set_headless
set_paths(browser_path=r'/opt/google/chrome/google-chrome') #一般linux安装的google浏览器默认都在这个目录
set_headless(True)

co = ChromiumOptions()
co.set_proxy('xx')

co.set_argument('--incognito')
co.set_argument('--no-sandbox')

page = WebPage(mode='d', driver_or_options=co)
page.get('https://ipinfo.io/json')

print(page.html)

"""

drissionpage ==  3.2.34

**Comment by g1879** [comment]
这个功能是正常的，你再检查一下，但只支持http和https，而且不带用户名和密码的代理。

**Comment by Sleeeepy7** [comment]
> 这个功能是正常的，你再检查一下，但只支持http和https，而且不带用户名和密码的代理。

Sorry, I couldn’t find any documentation on your methods or usage, can you tell me where I can find documentation or examples?
Unfortunately I don't know Chinese but I really liked your lib

**Comment by g1879** [comment]
> > 这个功能是正常的，你再检查一下，但只支持http和https，而且不带用户名和密码的代理。
> 
> Sorry, I couldn’t find any documentation on your methods or usage, can you tell me where I can find documentation or examples? Unfortunately I don't know Chinese but I really liked your lib

很抱歉我现在还没写关于代理的使用示例。
我一般用插件的方式使用代理，以便随时更换IP。我常用SwitchyOmega，用一个tab对象专门负责控制它的设置页面去修改ip，但现在还没有时间写使用案例。迟点应该会在文档里添加。
由于我自己时间有限，现在还没有英文文档，最新版的中文文档在这里：https://g1879.gitee.io/beta4/

**Comment by wjsw1781** [comment]
centos下 我是集群里面的机器  没有画面  add_extension 没有效果,拿到的截图查看情况
![image](https://github.com/g1879/DrissionPage/assets/28215744/4696f015-4b52-4584-939b-db6cdaf9860b)
导致所有对proxy插件的修改和配置都无法访问到

window上我已经全部测试好了 都没问题,但是集群全是linux没有画面那种,只能无头,此时就会出现上面插件没效果的情况
有没有大佬遇到?

**Comment by wjsw1781** [comment]
![image](https://github.com/g1879/DrissionPage/assets/28215744/931b3517-9190-4ea5-9c3b-9edc466c6fe1)

**Comment by wjsw1781** [comment]
![image](https://github.com/g1879/DrissionPage/assets/28215744/7ea4f5a4-af6a-4547-89cd-6f308245d8ec)
同样的代码在window上没啥问题
Linux上插件就是没反应  是不是cdp的bug?

**Comment by liudhzhyym** [comment]
同样的问题，linux下add_extension 不生效，浏览器启动后没有插件

**Comment by liudhzhyym** [comment]
找到问题了，用老版本的就没问题了
