### ISSUE TITLE
请问是否可实现拦截发送前的request和渲染前的response

### ISSUE THREAD

**Issue by zhaoxilingcheng** [g1879/DrissionPage#7]
拦截发送前的request和渲染前的response

**Comment by zhaoxilingcheng** [comment]
类似于， 利用mitmproxy启动代理，去拦截请求和响应

**Comment by g1879** [comment]
[http://g1879.gitee.io/flowviewer/#/README](http://g1879.gitee.io/flowviewer/#/README)
我另外写了一个库，可以监听发出去和收回来的数据包。

**Comment by zhaoxilingcheng** [comment]
> http://g1879.gitee.io/flowviewer/#/README 我另外写了一个库，可以监听发出去和收回来的数据包。

这个很棒，可惜只是监听，没有做拦截功能。 mitmproxy可以aop请求和响应

**Comment by g1879** [comment]
> > http://g1879.gitee.io/flowviewer/#/README 我另外写了一个库，可以监听发出去和收回来的数据包。
> 
> 这个很棒，可惜只是监听，没有做拦截功能。 mitmproxy可以aop请求和响应

怕被请去喝茶，拦截和修改请求就不做了。

**Comment by maryjeck** [comment]
> > > http://g1879.gitee.io/flowviewer/#/README 我另外写了一个库，可以监听发出去和收回来的数据包。
> > 
> > 
> > 这个很棒，可惜只是监听，没有做拦截功能。 mitmproxy可以aop请求和响应
> 
> 怕被请去喝茶，拦截和修改请求就不做了。

这个不会吧，playright就可以拦截，并修改请求，这个是正常的需求吧
