### ISSUE TITLE
[bug] ele.switch on a react element

### ISSUE THREAD

**Issue by tatar0071** [g1879/DrissionPage#70]
In React dropdowns, dispatched event UIEvent("switch") is ignored on https://twitch.tv.
So ele.switch only client-side changing the dropdown value and it's getting reset when you type something in other field.
Temp fix to properly fire change event:
```py
bms = signup_form.ele('@data-a-target=birthday-month-select')
eles = bms.eles("xpath://option")
eles[random.randrange(1, 12)].run_js('this.selected = true')
bms.run_js('this.dispatchEvent(new Event("change", {bubbles: true}))')
```

**Comment by g1879** [comment]
Thank you!
