### ISSUE TITLE
开启监听功能后，停止监听再关闭浏览器会报错且无法捕获

### ISSUE THREAD

**Issue by zhengbangze** [g1879/DrissionPage#73]
开启监听功能后，停止监听再关闭浏览器会报错且无法捕获，希望有空能解决下
![image](https://github.com/g1879/DrissionPage/assets/141294353/51f3b131-605c-4da1-b919-36393bf91570)

**Comment by g1879** [comment]
是的，不过之后的新版DrissionPage内置了更好的监听器，用新的比较好。

**Comment by HkerVit** [comment]
> 是的，不过之后的新版DrissionPage内置了更好的监听器，用新的比较好。

please help: Load and save cookies SIR.
