### ISSUE TITLE
Chromium Page in AWS Lambda

### ISSUE THREAD

**Issue by rubensm33** [g1879/DrissionPage#79]
I want to use ChromiumPage in an AWS Lambda function. To do this, I built the image in an ECR repository and linked it with my lambda. But I am facing this error: "errorMessage": "\n连接浏览器失败，可能原因：\n1、浏览器未启动\n2、9222端口不是Chromium内核浏览器\n3、该浏览器未允许控制\n4、 "ChromiumOptions指定别的端口和指定浏览器路径",
  "errorType": "BrowserConnectError".
Do you have any recommendations for configuring a lambda or container or ChromiumPage itself so that it can run on an AWS Lambda?

**Comment by g1879** [comment]
我没有用过AWS Lambda，不是很清楚。
