### ISSUE TITLE
问题求助：如何得到某页面加载完成后的源码

### ISSUE THREAD

**Issue by cws999** [g1879/DrissionPage#81]
我使用Edge打开页面https://www.douyin.com/user/MS4wLjABAAAAf3oGow67tNuD2yXHiIFmd5PUaVfvFbBKDF21Peq6iIs，拉到底部，使其全部加载
然后执行下面的两个操作
1 点击鼠标右键“查看页面源代码”
2 按F12 ，在“元素”标签的源代码，与第一步看到的代码是不一样的
那么如何得到第二步的源代码呢？？

**Comment by chahualao** [comment]
使用d模式，可以运行js，动态加载内容

**Comment by g1879** [comment]
page.html
