### ISSUE TITLE
我如何才能每次都打开全新干净的 Chrome 浏览器？

### ISSUE THREAD

**Issue by TigSZar** [g1879/DrissionPage#86]
你好 。

我如何打开新的 chrome 实例，不存储 cookie、缓存或历史记录，并且不使用默认的 ini 配置？

怎样才能做到这一点呢？

**Comment by cws999** [comment]
我现在每次打开都是全新干净的浏览器，想用浏览器的配置都不行

**Comment by g1879** [comment]
使用auto_port()
