### ISSUE TITLE
安装时报错：Could not find a version that satisfies the requirement click~=8.1.3 (from DrissionPage)

### ISSUE THREAD

**Issue by peterlinux2010** [g1879/DrissionPage#9]
你好，请问在安装时报以下错误，是什么问题？
指定固定版本安装也是一样的（pip install DrissionPage==3.2.24 --upgrade）
pip install DrissionPage

Collecting DrissionPage
  Using cached https://files.pythonhosted.org/packages/db/a5/9731a011f010377d4dc1395651f25e2a6e3559f01564101b348f402f47ae/DrissionPage-3.2.26-py3-none-any.whl
Collecting lxml (from DrissionPage)
  Using cached https://files.pythonhosted.org/packages/96/57/1f945e3f8068a5b2a299a10946dfe0c192c701bd707d2bada0e81c0067eb/lxml-4.9.2-cp36-cp36m-win_amd64.whl
Collecting websocket-client (from DrissionPage)
  Using cached https://files.pythonhosted.org/packages/35/21/8614b6de7c35d0bc584da13c45b8b08e404eee28a0504c1d00f5e1aa0a23/websocket_client-1.3.1-py3-none-any.whl
Collecting click~=8.1.3 (from DrissionPage)
  Could not find a version that satisfies the requirement click~=8.1.3 (from DrissionPage) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.5.1, 0.6, 0.7, 1.0, 1.1, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 3.0, 3.1, 3.2, 3.3, 4.0, 4.1, 5.0, 5.1, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7.dev0, 6.7, 7.0, 7.1, 7.1.1, 7.1.2, 8.0.0a1, 8.0.0rc1, 8.0.0, 8.0.1, 8.0.2, 8.0.3, 8.0.4)
No matching distribution found for click~=8.1.3 (from DrissionPage)
You are using pip version 18.1, however version 21.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by g1879** [comment]
嗯，要pytohn3.7才能支持。下个版本我尝试改回支持python3.6。现在最新版是3.2.26。

**Comment by g1879** [comment]
已发布3.2.27，恢复对3.6支持。
