### ISSUE TITLE
Element input start at wrong position

### ISSUE THREAD

**Issue by HappyGroupHub** [g1879/DrissionPage#92]
While using these code to input login code
```
input_box = new_tab.ele("xpath://input")
input_box.input('123456', clear=True)
```
The input always start at the second position as the image provided
![image](https://github.com/g1879/DrissionPage/assets/43276256/d3dce63d-c97b-4d79-8c8c-b50c8091d0b7)

While using selenium, the same locate code with `send_keys()` works fine instead
So I assume the problem is not from the website but the `Element.input()` function

Thanks.

**Comment by g1879** [comment]
可以把网址发给我测试一下吗？谢谢。

**Comment by HappyGroupHub** [comment]
這個網頁必須要有Surfshark的帳號才可登入，你應該用不了[網站](https://my.surfshark.com/account/login-code)
因此 我幫你抓取相關的html code試試
```<div class="HlWba HAF99"><div data-test="content-layout-overline" class="JQ3iS Vz_wI">Log in with code</div><div data-test="content-layout-title" class="JQ3iS V4HEa">Enter login code</div><div data-test="content-layout-description" class="JQ3iS vtLgj">Login codes are found on the login screens of all our apps.<br>Enter a code to log in on that device.</div><div class="sMkBZ"><div class="w33Bx"><span data-test="2fa-input-wrapper" class="QWcNV"><input data-index="0" value="" type="text" pattern="[0-9A-Za-z]{1}" inputmode="text" autocomplete="off" class="Koiq5 S8ABe"><span class="r4Z6Y"></span></span><span data-test="2fa-input-wrapper" class="QWcNV"><input data-index="1" value="" type="text" pattern="[0-9A-Za-z]{1}" inputmode="text" autocomplete="off" class="Koiq5 S8ABe"><span class="r4Z6Y"></span></span><span data-test="2fa-input-wrapper" class="QWcNV"><input data-index="2" value="" type="text" pattern="[0-9A-Za-z]{1}" inputmode="text" autocomplete="off" class="Koiq5 S8ABe"><span class="r4Z6Y"></span></span><span data-test="2fa-input-wrapper" class="QWcNV"><input data-index="3" value="" type="text" pattern="[0-9A-Za-z]{1}" inputmode="text" autocomplete="off" class="Koiq5 S8ABe"><span class="r4Z6Y"></span></span><span data-test="2fa-input-wrapper" class="QWcNV"><input data-index="4" value="" type="text" pattern="[0-9A-Za-z]{1}" inputmode="text" autocomplete="off" class="Koiq5 S8ABe"><span class="r4Z6Y"></span></span><span data-test="2fa-input-wrapper" class="QWcNV"><input data-index="5" value="" type="text" pattern="[0-9A-Za-z]{1}" inputmode="text" autocomplete="off" class="Koiq5 S8ABe"><span class="r4Z6Y"></span></span></div></div><div class="JQ3iS LODZ5"><button type="submit" disabled="" tabindex="1" data-test="submit-button" class="bmbVK PpOaN">Log in</button><a href="/account/settings" tabindex="0" data-test="back-button" class="fSw5M _FMnt">Back</a></div></div>```

**Comment by HappyGroupHub** [comment]
Problem solved by @g1879 at [Gitee Issues](https://gitee.com/g1879/DrissionPage/issues/I8OXZL)

Solution:
`ele.input(clear=False)`

Author Commented:
The default `clear=True` arg with `input()` func in Element Object will lead to wrong positioning, simply specify it to False will solve the problem.
