### ISSUE TITLE
Demo 无法运行

### ISSUE THREAD

**Issue by g-bo-wen** [g1879/DrissionPage#94]
Demo 地址: https://g1879.gitee.io/beta4/get_start/examples/data_packets/#_1
使用 page.eles() 时报错:
  File "/Users//venv/Drission/lib/python3.9/site-packages/DrissionPage/session_element.py", line 345, in make_session_ele
    html_or_ele = fromstring(html_or_ele.html)
  File "/Users//venv/Drission/lib/python3.9/site-packages/lxml/html/__init__.py", line 873, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users//venv/Drission/lib/python3.9/site-packages/lxml/html/__init__.py", line 761, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty
但是 
print(page.html) 是有数据的

**Comment by g1879** [comment]
升级4.0.0b26试试。
pip install DrissionPage==4.0.0b26

**Comment by g-bo-wen** [comment]
> 升级4.0.0b26试试。 pip install DrissionPage==4.0.0b26

也是有问题的: 
page.get() 后 print(page.html) 是有打印网页内容的
依赖: 
certifi            2023.11.17
charset-normalizer 3.3.2
click              8.1.7
cssselect          1.2.0
DataRecorder       3.4.9
DownloadKit        2.0.0b1
DrissionPage       4.0.0b26
et-xmlfile         1.1.0
filelock           3.13.1
idna               3.6
lxml               4.9.4
openpyxl           3.1.2
pip                23.2.1
psutil             5.9.7
requests           2.31.0
requests-file      1.5.1
setuptools         68.2.0
six                1.16.0
tldextract         5.1.1
urllib3            2.1.0
websocket-client   1.7.0
wheel              0.41.2

![AAAA7348-08C8-47F0-803A-4FEFC40F587E](https://github.com/g1879/DrissionPage/assets/29349344/3793fcf2-d18d-4cfa-b19a-4702ab9f5dda)

**Comment by yangzhao5566** [comment]
也遇到了同样的问题，依赖
Package            Version
------------------ ----------
certifi            2023.11.17
charset-normalizer 3.3.2
click              8.1.7
cssselect          1.2.0
DataRecorder       3.4.9
DownloadKit        2.0.0b2
DrissionPage       4.0.0b26
et-xmlfile         1.1.0
filelock           3.13.1
FlowViewer         0.3.0
idna               3.6
lxml               4.9.4
openpyxl           3.1.2
pip                23.3.2
psutil             5.9.7
pychrome           0.2.4
requests           2.31.0
requests-file      1.5.1
setuptools         69.0.3
six                1.16.0
tldextract         5.1.1
urllib3            2.1.0
websocket-client   1.7.0

系统 macos  12.6.1 (21G217

**Comment by fantasyao** [comment]
我也遇到了这个问题, 奇怪的是。当我关闭了clash代理后，就能访问目标网址，并打印成功，一旦开启clash代理，就提示`ParserError: Document is empty`
报错截图：
![image](https://github.com/g1879/DrissionPage/assets/111344085/fdb98320-07d0-4197-81b3-d636ad8f8113)

然后我按照使用文档设置了代理，但是依旧无法打印出来元素，必须得关闭clash代理后，才可以。我也按照回复，安装了pip install DrissionPage==4.0.0b26，也不行，下面是我的代码：

```
from DrissionPage import SessionPage
from DrissionPage import SessionOptions # 用于管理启动配置

# 创建配置对象
so =  SessionOptions()
# 设置代理
so.set_proxies(http='http://127.0.0.1:7890', https='http://127.0.0.1:7890')

page2 = SessionPage(session_or_options=so) # 传入配置对象 

 # 我根据使用文档，用另外一种方式添加的代理，我单独设置，同时设置都不行。
page2.set.proxies( http='http://localhost:7890',https='http://localhost:7890' )


page2.get('https://www.cnblogs.com/alltests')
# .表示按class属性查找元素。
links = page2.eles('.postTitle2 vertical-middle')



for link in links:
    print(link.text)  # .link获取元素的href或src属性。

```

**Comment by wyj2046** [comment]
升级一下lxml版本可以解决
