### ISSUE TITLE
Why is this command not returning expected results

### ISSUE THREAD

**Issue by M2ATrail** [g1879/DrissionPage#95]
Hello, I'd like to thank you for this project and apologize for not being able to read Chinese.
I've been using this to scrape indeed job site for personal usage https://github.com/ultrafunkamsterdam/undetected-chromedriver/
but past week or two it stopped working, and I came across your project.
it seems like you had english docs in 1.6.0 but api was changed, I'm not able to use the driveroptions to set the same driver settings even passing them to `addr_driver_opts`, I can pass this but when i try to set the driver options it doesn't accept it, 
```
dp_options = dp.ChromiumOptions()
dp_options.set_paths(browser_path=browser_binary_path,
                     user_data_path=browser_user_data_path)
```

in the old lib (UC) I was able to get mhtml archive using `mhtml = driver.execute_cdp_cmd('Page.captureSnapshot', {})`
but and in your lib I did `mhtml = driver.run_cdp_loaded('Page.captureSnapshot')["data"]` but trying to open the files itself doesn't seem to be working for some reason, even though inside is the same structure, your have a bit extra spacing though for some reason.

I've decided to just not save page source in my own use case, but it might be worth looking into.

another thing I noticed is that you have different naming conviction from typical selenium based libraries, like driver.html instead of driver.page_source that would be beneficial to have it standardized but not a big priority if it is working for your uses.

thanks again.

**Comment by g1879** [comment]
谢谢你的肯定。
使用请首先升级到4.0，`pip install DrissionPage==4.0.0b26`
4.0使用文档：http://g1879.gitee.io/beta4
4.0是一个重大升级，有很多变化。
我测试过`page.run_cdp('Page.captureSnapshot')`是可以使用的。

我英文不好，之前的英文文档是机器翻译的，后来没精力维护就删除了。
至于api名字，我认为selenium的命名太啰嗦了，而且对于英文不好的人有些单词过于复杂。因此我进行了很多简化。

**Comment by M2ATrail** [comment]
这也是机器翻译的。
我同意它很冗长，但其中很多内容都是从浏览器借用的，例如，如果您正在寻找一个元素，您将始终查看页面源/检查元素。
但如果它对你的目标受众有用并且有意义，那么就不需要改变它。


非常感谢您的回复并祝您周末愉快
